// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: agent.proto

package agentpbconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	agentpb "github.com/tmc/cove/proto/agentpb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AgentName is the fully-qualified name of the Agent service.
	AgentName = "vz.agent.v1.Agent"
	// UserAgentName is the fully-qualified name of the UserAgent service.
	UserAgentName = "vz.agent.v1.UserAgent"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AgentPingProcedure is the fully-qualified name of the Agent's Ping RPC.
	AgentPingProcedure = "/vz.agent.v1.Agent/Ping"
	// AgentInfoProcedure is the fully-qualified name of the Agent's Info RPC.
	AgentInfoProcedure = "/vz.agent.v1.Agent/Info"
	// AgentExecProcedure is the fully-qualified name of the Agent's Exec RPC.
	AgentExecProcedure = "/vz.agent.v1.Agent/Exec"
	// AgentExecStreamProcedure is the fully-qualified name of the Agent's ExecStream RPC.
	AgentExecStreamProcedure = "/vz.agent.v1.Agent/ExecStream"
	// AgentExecAttachProcedure is the fully-qualified name of the Agent's ExecAttach RPC.
	AgentExecAttachProcedure = "/vz.agent.v1.Agent/ExecAttach"
	// AgentResizeExecTTYProcedure is the fully-qualified name of the Agent's ResizeExecTTY RPC.
	AgentResizeExecTTYProcedure = "/vz.agent.v1.Agent/ResizeExecTTY"
	// AgentSignalExecProcedure is the fully-qualified name of the Agent's SignalExec RPC.
	AgentSignalExecProcedure = "/vz.agent.v1.Agent/SignalExec"
	// AgentSetTimeProcedure is the fully-qualified name of the Agent's SetTime RPC.
	AgentSetTimeProcedure = "/vz.agent.v1.Agent/SetTime"
	// AgentResizeMacOSAPFSProcedure is the fully-qualified name of the Agent's ResizeMacOSAPFS RPC.
	AgentResizeMacOSAPFSProcedure = "/vz.agent.v1.Agent/ResizeMacOSAPFS"
	// AgentCopyInProcedure is the fully-qualified name of the Agent's CopyIn RPC.
	AgentCopyInProcedure = "/vz.agent.v1.Agent/CopyIn"
	// AgentCopyOutProcedure is the fully-qualified name of the Agent's CopyOut RPC.
	AgentCopyOutProcedure = "/vz.agent.v1.Agent/CopyOut"
	// AgentWriteFileProcedure is the fully-qualified name of the Agent's WriteFile RPC.
	AgentWriteFileProcedure = "/vz.agent.v1.Agent/WriteFile"
	// AgentReadFileProcedure is the fully-qualified name of the Agent's ReadFile RPC.
	AgentReadFileProcedure = "/vz.agent.v1.Agent/ReadFile"
	// AgentMkdirProcedure is the fully-qualified name of the Agent's Mkdir RPC.
	AgentMkdirProcedure = "/vz.agent.v1.Agent/Mkdir"
	// AgentMountProcedure is the fully-qualified name of the Agent's Mount RPC.
	AgentMountProcedure = "/vz.agent.v1.Agent/Mount"
	// AgentUnmountProcedure is the fully-qualified name of the Agent's Unmount RPC.
	AgentUnmountProcedure = "/vz.agent.v1.Agent/Unmount"
	// AgentShutdownProcedure is the fully-qualified name of the Agent's Shutdown RPC.
	AgentShutdownProcedure = "/vz.agent.v1.Agent/Shutdown"
	// AgentRebootProcedure is the fully-qualified name of the Agent's Reboot RPC.
	AgentRebootProcedure = "/vz.agent.v1.Agent/Reboot"
	// UserAgentUserExecProcedure is the fully-qualified name of the UserAgent's UserExec RPC.
	UserAgentUserExecProcedure = "/vz.agent.v1.UserAgent/UserExec"
	// UserAgentUserExecStreamProcedure is the fully-qualified name of the UserAgent's UserExecStream
	// RPC.
	UserAgentUserExecStreamProcedure = "/vz.agent.v1.UserAgent/UserExecStream"
)

// AgentClient is a client for the vz.agent.v1.Agent service.
type AgentClient interface {
	// Ping checks that the agent is alive.
	Ping(context.Context, *connect.Request[agentpb.PingRequest]) (*connect.Response[agentpb.PingResponse], error)
	// Info returns guest system information.
	Info(context.Context, *connect.Request[agentpb.InfoRequest]) (*connect.Response[agentpb.InfoResponse], error)
	// Exec runs a command and waits for it to complete.
	Exec(context.Context, *connect.Request[agentpb.ExecRequest]) (*connect.Response[agentpb.ExecResponse], error)
	// ExecStream runs a command with streaming stdout/stderr.
	ExecStream(context.Context, *connect.Request[agentpb.ExecRequest]) (*connect.ServerStreamForClient[agentpb.ExecOutput], error)
	// ExecAttach runs a command with bidirectional stdin/stdout/stderr/control.
	ExecAttach(context.Context) *connect.BidiStreamForClient[agentpb.ExecAttachRequest, agentpb.ExecAttachOutput]
	ResizeExecTTY(context.Context, *connect.Request[agentpb.ResizeExecTTYRequest]) (*connect.Response[agentpb.ResizeExecTTYResponse], error)
	SignalExec(context.Context, *connect.Request[agentpb.SignalExecRequest]) (*connect.Response[agentpb.SignalExecResponse], error)
	SetTime(context.Context, *connect.Request[agentpb.SetTimeRequest]) (*connect.Response[agentpb.SetTimeResponse], error)
	// ResizeMacOSAPFS expands the macOS root APFS container after its backing disk grows.
	ResizeMacOSAPFS(context.Context, *connect.Request[agentpb.ResizeMacOSAPFSRequest]) (*connect.Response[agentpb.ResizeMacOSAPFSResponse], error)
	// CopyIn transfers a file from the host into the guest.
	CopyIn(context.Context) *connect.ClientStreamForClient[agentpb.CopyInChunk, agentpb.CopyInResponse]
	// CopyOut transfers a file from the guest to the host.
	CopyOut(context.Context, *connect.Request[agentpb.CopyOutRequest]) (*connect.ServerStreamForClient[agentpb.CopyOutChunk], error)
	// WriteFile writes data to a file in the guest.
	WriteFile(context.Context, *connect.Request[agentpb.WriteFileRequest]) (*connect.Response[agentpb.WriteFileResponse], error)
	// ReadFile reads a file from the guest.
	ReadFile(context.Context, *connect.Request[agentpb.ReadFileRequest]) (*connect.Response[agentpb.ReadFileResponse], error)
	// Mkdir creates a directory in the guest.
	Mkdir(context.Context, *connect.Request[agentpb.MkdirRequest]) (*connect.Response[agentpb.MkdirResponse], error)
	// Mount mounts a filesystem in the guest.
	Mount(context.Context, *connect.Request[agentpb.MountRequest]) (*connect.Response[agentpb.MountResponse], error)
	// Unmount unmounts a filesystem in the guest.
	Unmount(context.Context, *connect.Request[agentpb.UnmountRequest]) (*connect.Response[agentpb.UnmountResponse], error)
	// Shutdown initiates a graceful shutdown of the guest.
	Shutdown(context.Context, *connect.Request[agentpb.ShutdownRequest]) (*connect.Response[agentpb.ShutdownResponse], error)
	// Reboot initiates a guest reboot.
	Reboot(context.Context, *connect.Request[agentpb.RebootRequest]) (*connect.Response[agentpb.RebootResponse], error)
}

// NewAgentClient constructs a client for the vz.agent.v1.Agent service. By default, it uses the
// Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAgentClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AgentClient {
	baseURL = strings.TrimRight(baseURL, "/")
	agentMethods := agentpb.File_agent_proto.Services().ByName("Agent").Methods()
	return &agentClient{
		ping: connect.NewClient[agentpb.PingRequest, agentpb.PingResponse](
			httpClient,
			baseURL+AgentPingProcedure,
			connect.WithSchema(agentMethods.ByName("Ping")),
			connect.WithClientOptions(opts...),
		),
		info: connect.NewClient[agentpb.InfoRequest, agentpb.InfoResponse](
			httpClient,
			baseURL+AgentInfoProcedure,
			connect.WithSchema(agentMethods.ByName("Info")),
			connect.WithClientOptions(opts...),
		),
		exec: connect.NewClient[agentpb.ExecRequest, agentpb.ExecResponse](
			httpClient,
			baseURL+AgentExecProcedure,
			connect.WithSchema(agentMethods.ByName("Exec")),
			connect.WithClientOptions(opts...),
		),
		execStream: connect.NewClient[agentpb.ExecRequest, agentpb.ExecOutput](
			httpClient,
			baseURL+AgentExecStreamProcedure,
			connect.WithSchema(agentMethods.ByName("ExecStream")),
			connect.WithClientOptions(opts...),
		),
		execAttach: connect.NewClient[agentpb.ExecAttachRequest, agentpb.ExecAttachOutput](
			httpClient,
			baseURL+AgentExecAttachProcedure,
			connect.WithSchema(agentMethods.ByName("ExecAttach")),
			connect.WithClientOptions(opts...),
		),
		resizeExecTTY: connect.NewClient[agentpb.ResizeExecTTYRequest, agentpb.ResizeExecTTYResponse](
			httpClient,
			baseURL+AgentResizeExecTTYProcedure,
			connect.WithSchema(agentMethods.ByName("ResizeExecTTY")),
			connect.WithClientOptions(opts...),
		),
		signalExec: connect.NewClient[agentpb.SignalExecRequest, agentpb.SignalExecResponse](
			httpClient,
			baseURL+AgentSignalExecProcedure,
			connect.WithSchema(agentMethods.ByName("SignalExec")),
			connect.WithClientOptions(opts...),
		),
		setTime: connect.NewClient[agentpb.SetTimeRequest, agentpb.SetTimeResponse](
			httpClient,
			baseURL+AgentSetTimeProcedure,
			connect.WithSchema(agentMethods.ByName("SetTime")),
			connect.WithClientOptions(opts...),
		),
		resizeMacOSAPFS: connect.NewClient[agentpb.ResizeMacOSAPFSRequest, agentpb.ResizeMacOSAPFSResponse](
			httpClient,
			baseURL+AgentResizeMacOSAPFSProcedure,
			connect.WithSchema(agentMethods.ByName("ResizeMacOSAPFS")),
			connect.WithClientOptions(opts...),
		),
		copyIn: connect.NewClient[agentpb.CopyInChunk, agentpb.CopyInResponse](
			httpClient,
			baseURL+AgentCopyInProcedure,
			connect.WithSchema(agentMethods.ByName("CopyIn")),
			connect.WithClientOptions(opts...),
		),
		copyOut: connect.NewClient[agentpb.CopyOutRequest, agentpb.CopyOutChunk](
			httpClient,
			baseURL+AgentCopyOutProcedure,
			connect.WithSchema(agentMethods.ByName("CopyOut")),
			connect.WithClientOptions(opts...),
		),
		writeFile: connect.NewClient[agentpb.WriteFileRequest, agentpb.WriteFileResponse](
			httpClient,
			baseURL+AgentWriteFileProcedure,
			connect.WithSchema(agentMethods.ByName("WriteFile")),
			connect.WithClientOptions(opts...),
		),
		readFile: connect.NewClient[agentpb.ReadFileRequest, agentpb.ReadFileResponse](
			httpClient,
			baseURL+AgentReadFileProcedure,
			connect.WithSchema(agentMethods.ByName("ReadFile")),
			connect.WithClientOptions(opts...),
		),
		mkdir: connect.NewClient[agentpb.MkdirRequest, agentpb.MkdirResponse](
			httpClient,
			baseURL+AgentMkdirProcedure,
			connect.WithSchema(agentMethods.ByName("Mkdir")),
			connect.WithClientOptions(opts...),
		),
		mount: connect.NewClient[agentpb.MountRequest, agentpb.MountResponse](
			httpClient,
			baseURL+AgentMountProcedure,
			connect.WithSchema(agentMethods.ByName("Mount")),
			connect.WithClientOptions(opts...),
		),
		unmount: connect.NewClient[agentpb.UnmountRequest, agentpb.UnmountResponse](
			httpClient,
			baseURL+AgentUnmountProcedure,
			connect.WithSchema(agentMethods.ByName("Unmount")),
			connect.WithClientOptions(opts...),
		),
		shutdown: connect.NewClient[agentpb.ShutdownRequest, agentpb.ShutdownResponse](
			httpClient,
			baseURL+AgentShutdownProcedure,
			connect.WithSchema(agentMethods.ByName("Shutdown")),
			connect.WithClientOptions(opts...),
		),
		reboot: connect.NewClient[agentpb.RebootRequest, agentpb.RebootResponse](
			httpClient,
			baseURL+AgentRebootProcedure,
			connect.WithSchema(agentMethods.ByName("Reboot")),
			connect.WithClientOptions(opts...),
		),
	}
}

// agentClient implements AgentClient.
type agentClient struct {
	ping            *connect.Client[agentpb.PingRequest, agentpb.PingResponse]
	info            *connect.Client[agentpb.InfoRequest, agentpb.InfoResponse]
	exec            *connect.Client[agentpb.ExecRequest, agentpb.ExecResponse]
	execStream      *connect.Client[agentpb.ExecRequest, agentpb.ExecOutput]
	execAttach      *connect.Client[agentpb.ExecAttachRequest, agentpb.ExecAttachOutput]
	resizeExecTTY   *connect.Client[agentpb.ResizeExecTTYRequest, agentpb.ResizeExecTTYResponse]
	signalExec      *connect.Client[agentpb.SignalExecRequest, agentpb.SignalExecResponse]
	setTime         *connect.Client[agentpb.SetTimeRequest, agentpb.SetTimeResponse]
	resizeMacOSAPFS *connect.Client[agentpb.ResizeMacOSAPFSRequest, agentpb.ResizeMacOSAPFSResponse]
	copyIn          *connect.Client[agentpb.CopyInChunk, agentpb.CopyInResponse]
	copyOut         *connect.Client[agentpb.CopyOutRequest, agentpb.CopyOutChunk]
	writeFile       *connect.Client[agentpb.WriteFileRequest, agentpb.WriteFileResponse]
	readFile        *connect.Client[agentpb.ReadFileRequest, agentpb.ReadFileResponse]
	mkdir           *connect.Client[agentpb.MkdirRequest, agentpb.MkdirResponse]
	mount           *connect.Client[agentpb.MountRequest, agentpb.MountResponse]
	unmount         *connect.Client[agentpb.UnmountRequest, agentpb.UnmountResponse]
	shutdown        *connect.Client[agentpb.ShutdownRequest, agentpb.ShutdownResponse]
	reboot          *connect.Client[agentpb.RebootRequest, agentpb.RebootResponse]
}

// Ping calls vz.agent.v1.Agent.Ping.
func (c *agentClient) Ping(ctx context.Context, req *connect.Request[agentpb.PingRequest]) (*connect.Response[agentpb.PingResponse], error) {
	return c.ping.CallUnary(ctx, req)
}

// Info calls vz.agent.v1.Agent.Info.
func (c *agentClient) Info(ctx context.Context, req *connect.Request[agentpb.InfoRequest]) (*connect.Response[agentpb.InfoResponse], error) {
	return c.info.CallUnary(ctx, req)
}

// Exec calls vz.agent.v1.Agent.Exec.
func (c *agentClient) Exec(ctx context.Context, req *connect.Request[agentpb.ExecRequest]) (*connect.Response[agentpb.ExecResponse], error) {
	return c.exec.CallUnary(ctx, req)
}

// ExecStream calls vz.agent.v1.Agent.ExecStream.
func (c *agentClient) ExecStream(ctx context.Context, req *connect.Request[agentpb.ExecRequest]) (*connect.ServerStreamForClient[agentpb.ExecOutput], error) {
	return c.execStream.CallServerStream(ctx, req)
}

// ExecAttach calls vz.agent.v1.Agent.ExecAttach.
func (c *agentClient) ExecAttach(ctx context.Context) *connect.BidiStreamForClient[agentpb.ExecAttachRequest, agentpb.ExecAttachOutput] {
	return c.execAttach.CallBidiStream(ctx)
}

// ResizeExecTTY calls vz.agent.v1.Agent.ResizeExecTTY.
func (c *agentClient) ResizeExecTTY(ctx context.Context, req *connect.Request[agentpb.ResizeExecTTYRequest]) (*connect.Response[agentpb.ResizeExecTTYResponse], error) {
	return c.resizeExecTTY.CallUnary(ctx, req)
}

// SignalExec calls vz.agent.v1.Agent.SignalExec.
func (c *agentClient) SignalExec(ctx context.Context, req *connect.Request[agentpb.SignalExecRequest]) (*connect.Response[agentpb.SignalExecResponse], error) {
	return c.signalExec.CallUnary(ctx, req)
}

// SetTime calls vz.agent.v1.Agent.SetTime.
func (c *agentClient) SetTime(ctx context.Context, req *connect.Request[agentpb.SetTimeRequest]) (*connect.Response[agentpb.SetTimeResponse], error) {
	return c.setTime.CallUnary(ctx, req)
}

// ResizeMacOSAPFS calls vz.agent.v1.Agent.ResizeMacOSAPFS.
func (c *agentClient) ResizeMacOSAPFS(ctx context.Context, req *connect.Request[agentpb.ResizeMacOSAPFSRequest]) (*connect.Response[agentpb.ResizeMacOSAPFSResponse], error) {
	return c.resizeMacOSAPFS.CallUnary(ctx, req)
}

// CopyIn calls vz.agent.v1.Agent.CopyIn.
func (c *agentClient) CopyIn(ctx context.Context) *connect.ClientStreamForClient[agentpb.CopyInChunk, agentpb.CopyInResponse] {
	return c.copyIn.CallClientStream(ctx)
}

// CopyOut calls vz.agent.v1.Agent.CopyOut.
func (c *agentClient) CopyOut(ctx context.Context, req *connect.Request[agentpb.CopyOutRequest]) (*connect.ServerStreamForClient[agentpb.CopyOutChunk], error) {
	return c.copyOut.CallServerStream(ctx, req)
}

// WriteFile calls vz.agent.v1.Agent.WriteFile.
func (c *agentClient) WriteFile(ctx context.Context, req *connect.Request[agentpb.WriteFileRequest]) (*connect.Response[agentpb.WriteFileResponse], error) {
	return c.writeFile.CallUnary(ctx, req)
}

// ReadFile calls vz.agent.v1.Agent.ReadFile.
func (c *agentClient) ReadFile(ctx context.Context, req *connect.Request[agentpb.ReadFileRequest]) (*connect.Response[agentpb.ReadFileResponse], error) {
	return c.readFile.CallUnary(ctx, req)
}

// Mkdir calls vz.agent.v1.Agent.Mkdir.
func (c *agentClient) Mkdir(ctx context.Context, req *connect.Request[agentpb.MkdirRequest]) (*connect.Response[agentpb.MkdirResponse], error) {
	return c.mkdir.CallUnary(ctx, req)
}

// Mount calls vz.agent.v1.Agent.Mount.
func (c *agentClient) Mount(ctx context.Context, req *connect.Request[agentpb.MountRequest]) (*connect.Response[agentpb.MountResponse], error) {
	return c.mount.CallUnary(ctx, req)
}

// Unmount calls vz.agent.v1.Agent.Unmount.
func (c *agentClient) Unmount(ctx context.Context, req *connect.Request[agentpb.UnmountRequest]) (*connect.Response[agentpb.UnmountResponse], error) {
	return c.unmount.CallUnary(ctx, req)
}

// Shutdown calls vz.agent.v1.Agent.Shutdown.
func (c *agentClient) Shutdown(ctx context.Context, req *connect.Request[agentpb.ShutdownRequest]) (*connect.Response[agentpb.ShutdownResponse], error) {
	return c.shutdown.CallUnary(ctx, req)
}

// Reboot calls vz.agent.v1.Agent.Reboot.
func (c *agentClient) Reboot(ctx context.Context, req *connect.Request[agentpb.RebootRequest]) (*connect.Response[agentpb.RebootResponse], error) {
	return c.reboot.CallUnary(ctx, req)
}

// AgentHandler is an implementation of the vz.agent.v1.Agent service.
type AgentHandler interface {
	// Ping checks that the agent is alive.
	Ping(context.Context, *connect.Request[agentpb.PingRequest]) (*connect.Response[agentpb.PingResponse], error)
	// Info returns guest system information.
	Info(context.Context, *connect.Request[agentpb.InfoRequest]) (*connect.Response[agentpb.InfoResponse], error)
	// Exec runs a command and waits for it to complete.
	Exec(context.Context, *connect.Request[agentpb.ExecRequest]) (*connect.Response[agentpb.ExecResponse], error)
	// ExecStream runs a command with streaming stdout/stderr.
	ExecStream(context.Context, *connect.Request[agentpb.ExecRequest], *connect.ServerStream[agentpb.ExecOutput]) error
	// ExecAttach runs a command with bidirectional stdin/stdout/stderr/control.
	ExecAttach(context.Context, *connect.BidiStream[agentpb.ExecAttachRequest, agentpb.ExecAttachOutput]) error
	ResizeExecTTY(context.Context, *connect.Request[agentpb.ResizeExecTTYRequest]) (*connect.Response[agentpb.ResizeExecTTYResponse], error)
	SignalExec(context.Context, *connect.Request[agentpb.SignalExecRequest]) (*connect.Response[agentpb.SignalExecResponse], error)
	SetTime(context.Context, *connect.Request[agentpb.SetTimeRequest]) (*connect.Response[agentpb.SetTimeResponse], error)
	// ResizeMacOSAPFS expands the macOS root APFS container after its backing disk grows.
	ResizeMacOSAPFS(context.Context, *connect.Request[agentpb.ResizeMacOSAPFSRequest]) (*connect.Response[agentpb.ResizeMacOSAPFSResponse], error)
	// CopyIn transfers a file from the host into the guest.
	CopyIn(context.Context, *connect.ClientStream[agentpb.CopyInChunk]) (*connect.Response[agentpb.CopyInResponse], error)
	// CopyOut transfers a file from the guest to the host.
	CopyOut(context.Context, *connect.Request[agentpb.CopyOutRequest], *connect.ServerStream[agentpb.CopyOutChunk]) error
	// WriteFile writes data to a file in the guest.
	WriteFile(context.Context, *connect.Request[agentpb.WriteFileRequest]) (*connect.Response[agentpb.WriteFileResponse], error)
	// ReadFile reads a file from the guest.
	ReadFile(context.Context, *connect.Request[agentpb.ReadFileRequest]) (*connect.Response[agentpb.ReadFileResponse], error)
	// Mkdir creates a directory in the guest.
	Mkdir(context.Context, *connect.Request[agentpb.MkdirRequest]) (*connect.Response[agentpb.MkdirResponse], error)
	// Mount mounts a filesystem in the guest.
	Mount(context.Context, *connect.Request[agentpb.MountRequest]) (*connect.Response[agentpb.MountResponse], error)
	// Unmount unmounts a filesystem in the guest.
	Unmount(context.Context, *connect.Request[agentpb.UnmountRequest]) (*connect.Response[agentpb.UnmountResponse], error)
	// Shutdown initiates a graceful shutdown of the guest.
	Shutdown(context.Context, *connect.Request[agentpb.ShutdownRequest]) (*connect.Response[agentpb.ShutdownResponse], error)
	// Reboot initiates a guest reboot.
	Reboot(context.Context, *connect.Request[agentpb.RebootRequest]) (*connect.Response[agentpb.RebootResponse], error)
}

// NewAgentHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAgentHandler(svc AgentHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	agentMethods := agentpb.File_agent_proto.Services().ByName("Agent").Methods()
	agentPingHandler := connect.NewUnaryHandler(
		AgentPingProcedure,
		svc.Ping,
		connect.WithSchema(agentMethods.ByName("Ping")),
		connect.WithHandlerOptions(opts...),
	)
	agentInfoHandler := connect.NewUnaryHandler(
		AgentInfoProcedure,
		svc.Info,
		connect.WithSchema(agentMethods.ByName("Info")),
		connect.WithHandlerOptions(opts...),
	)
	agentExecHandler := connect.NewUnaryHandler(
		AgentExecProcedure,
		svc.Exec,
		connect.WithSchema(agentMethods.ByName("Exec")),
		connect.WithHandlerOptions(opts...),
	)
	agentExecStreamHandler := connect.NewServerStreamHandler(
		AgentExecStreamProcedure,
		svc.ExecStream,
		connect.WithSchema(agentMethods.ByName("ExecStream")),
		connect.WithHandlerOptions(opts...),
	)
	agentExecAttachHandler := connect.NewBidiStreamHandler(
		AgentExecAttachProcedure,
		svc.ExecAttach,
		connect.WithSchema(agentMethods.ByName("ExecAttach")),
		connect.WithHandlerOptions(opts...),
	)
	agentResizeExecTTYHandler := connect.NewUnaryHandler(
		AgentResizeExecTTYProcedure,
		svc.ResizeExecTTY,
		connect.WithSchema(agentMethods.ByName("ResizeExecTTY")),
		connect.WithHandlerOptions(opts...),
	)
	agentSignalExecHandler := connect.NewUnaryHandler(
		AgentSignalExecProcedure,
		svc.SignalExec,
		connect.WithSchema(agentMethods.ByName("SignalExec")),
		connect.WithHandlerOptions(opts...),
	)
	agentSetTimeHandler := connect.NewUnaryHandler(
		AgentSetTimeProcedure,
		svc.SetTime,
		connect.WithSchema(agentMethods.ByName("SetTime")),
		connect.WithHandlerOptions(opts...),
	)
	agentResizeMacOSAPFSHandler := connect.NewUnaryHandler(
		AgentResizeMacOSAPFSProcedure,
		svc.ResizeMacOSAPFS,
		connect.WithSchema(agentMethods.ByName("ResizeMacOSAPFS")),
		connect.WithHandlerOptions(opts...),
	)
	agentCopyInHandler := connect.NewClientStreamHandler(
		AgentCopyInProcedure,
		svc.CopyIn,
		connect.WithSchema(agentMethods.ByName("CopyIn")),
		connect.WithHandlerOptions(opts...),
	)
	agentCopyOutHandler := connect.NewServerStreamHandler(
		AgentCopyOutProcedure,
		svc.CopyOut,
		connect.WithSchema(agentMethods.ByName("CopyOut")),
		connect.WithHandlerOptions(opts...),
	)
	agentWriteFileHandler := connect.NewUnaryHandler(
		AgentWriteFileProcedure,
		svc.WriteFile,
		connect.WithSchema(agentMethods.ByName("WriteFile")),
		connect.WithHandlerOptions(opts...),
	)
	agentReadFileHandler := connect.NewUnaryHandler(
		AgentReadFileProcedure,
		svc.ReadFile,
		connect.WithSchema(agentMethods.ByName("ReadFile")),
		connect.WithHandlerOptions(opts...),
	)
	agentMkdirHandler := connect.NewUnaryHandler(
		AgentMkdirProcedure,
		svc.Mkdir,
		connect.WithSchema(agentMethods.ByName("Mkdir")),
		connect.WithHandlerOptions(opts...),
	)
	agentMountHandler := connect.NewUnaryHandler(
		AgentMountProcedure,
		svc.Mount,
		connect.WithSchema(agentMethods.ByName("Mount")),
		connect.WithHandlerOptions(opts...),
	)
	agentUnmountHandler := connect.NewUnaryHandler(
		AgentUnmountProcedure,
		svc.Unmount,
		connect.WithSchema(agentMethods.ByName("Unmount")),
		connect.WithHandlerOptions(opts...),
	)
	agentShutdownHandler := connect.NewUnaryHandler(
		AgentShutdownProcedure,
		svc.Shutdown,
		connect.WithSchema(agentMethods.ByName("Shutdown")),
		connect.WithHandlerOptions(opts...),
	)
	agentRebootHandler := connect.NewUnaryHandler(
		AgentRebootProcedure,
		svc.Reboot,
		connect.WithSchema(agentMethods.ByName("Reboot")),
		connect.WithHandlerOptions(opts...),
	)
	return "/vz.agent.v1.Agent/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AgentPingProcedure:
			agentPingHandler.ServeHTTP(w, r)
		case AgentInfoProcedure:
			agentInfoHandler.ServeHTTP(w, r)
		case AgentExecProcedure:
			agentExecHandler.ServeHTTP(w, r)
		case AgentExecStreamProcedure:
			agentExecStreamHandler.ServeHTTP(w, r)
		case AgentExecAttachProcedure:
			agentExecAttachHandler.ServeHTTP(w, r)
		case AgentResizeExecTTYProcedure:
			agentResizeExecTTYHandler.ServeHTTP(w, r)
		case AgentSignalExecProcedure:
			agentSignalExecHandler.ServeHTTP(w, r)
		case AgentSetTimeProcedure:
			agentSetTimeHandler.ServeHTTP(w, r)
		case AgentResizeMacOSAPFSProcedure:
			agentResizeMacOSAPFSHandler.ServeHTTP(w, r)
		case AgentCopyInProcedure:
			agentCopyInHandler.ServeHTTP(w, r)
		case AgentCopyOutProcedure:
			agentCopyOutHandler.ServeHTTP(w, r)
		case AgentWriteFileProcedure:
			agentWriteFileHandler.ServeHTTP(w, r)
		case AgentReadFileProcedure:
			agentReadFileHandler.ServeHTTP(w, r)
		case AgentMkdirProcedure:
			agentMkdirHandler.ServeHTTP(w, r)
		case AgentMountProcedure:
			agentMountHandler.ServeHTTP(w, r)
		case AgentUnmountProcedure:
			agentUnmountHandler.ServeHTTP(w, r)
		case AgentShutdownProcedure:
			agentShutdownHandler.ServeHTTP(w, r)
		case AgentRebootProcedure:
			agentRebootHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAgentHandler returns CodeUnimplemented from all methods.
type UnimplementedAgentHandler struct{}

func (UnimplementedAgentHandler) Ping(context.Context, *connect.Request[agentpb.PingRequest]) (*connect.Response[agentpb.PingResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vz.agent.v1.Agent.Ping is not implemented"))
}

func (UnimplementedAgentHandler) Info(context.Context, *connect.Request[agentpb.InfoRequest]) (*connect.Response[agentpb.InfoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vz.agent.v1.Agent.Info is not implemented"))
}

func (UnimplementedAgentHandler) Exec(context.Context, *connect.Request[agentpb.ExecRequest]) (*connect.Response[agentpb.ExecResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vz.agent.v1.Agent.Exec is not implemented"))
}

func (UnimplementedAgentHandler) ExecStream(context.Context, *connect.Request[agentpb.ExecRequest], *connect.ServerStream[agentpb.ExecOutput]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("vz.agent.v1.Agent.ExecStream is not implemented"))
}

func (UnimplementedAgentHandler) ExecAttach(context.Context, *connect.BidiStream[agentpb.ExecAttachRequest, agentpb.ExecAttachOutput]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("vz.agent.v1.Agent.ExecAttach is not implemented"))
}

func (UnimplementedAgentHandler) ResizeExecTTY(context.Context, *connect.Request[agentpb.ResizeExecTTYRequest]) (*connect.Response[agentpb.ResizeExecTTYResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vz.agent.v1.Agent.ResizeExecTTY is not implemented"))
}

func (UnimplementedAgentHandler) SignalExec(context.Context, *connect.Request[agentpb.SignalExecRequest]) (*connect.Response[agentpb.SignalExecResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vz.agent.v1.Agent.SignalExec is not implemented"))
}

func (UnimplementedAgentHandler) SetTime(context.Context, *connect.Request[agentpb.SetTimeRequest]) (*connect.Response[agentpb.SetTimeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vz.agent.v1.Agent.SetTime is not implemented"))
}

func (UnimplementedAgentHandler) ResizeMacOSAPFS(context.Context, *connect.Request[agentpb.ResizeMacOSAPFSRequest]) (*connect.Response[agentpb.ResizeMacOSAPFSResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vz.agent.v1.Agent.ResizeMacOSAPFS is not implemented"))
}

func (UnimplementedAgentHandler) CopyIn(context.Context, *connect.ClientStream[agentpb.CopyInChunk]) (*connect.Response[agentpb.CopyInResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vz.agent.v1.Agent.CopyIn is not implemented"))
}

func (UnimplementedAgentHandler) CopyOut(context.Context, *connect.Request[agentpb.CopyOutRequest], *connect.ServerStream[agentpb.CopyOutChunk]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("vz.agent.v1.Agent.CopyOut is not implemented"))
}

func (UnimplementedAgentHandler) WriteFile(context.Context, *connect.Request[agentpb.WriteFileRequest]) (*connect.Response[agentpb.WriteFileResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vz.agent.v1.Agent.WriteFile is not implemented"))
}

func (UnimplementedAgentHandler) ReadFile(context.Context, *connect.Request[agentpb.ReadFileRequest]) (*connect.Response[agentpb.ReadFileResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vz.agent.v1.Agent.ReadFile is not implemented"))
}

func (UnimplementedAgentHandler) Mkdir(context.Context, *connect.Request[agentpb.MkdirRequest]) (*connect.Response[agentpb.MkdirResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vz.agent.v1.Agent.Mkdir is not implemented"))
}

func (UnimplementedAgentHandler) Mount(context.Context, *connect.Request[agentpb.MountRequest]) (*connect.Response[agentpb.MountResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vz.agent.v1.Agent.Mount is not implemented"))
}

func (UnimplementedAgentHandler) Unmount(context.Context, *connect.Request[agentpb.UnmountRequest]) (*connect.Response[agentpb.UnmountResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vz.agent.v1.Agent.Unmount is not implemented"))
}

func (UnimplementedAgentHandler) Shutdown(context.Context, *connect.Request[agentpb.ShutdownRequest]) (*connect.Response[agentpb.ShutdownResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vz.agent.v1.Agent.Shutdown is not implemented"))
}

func (UnimplementedAgentHandler) Reboot(context.Context, *connect.Request[agentpb.RebootRequest]) (*connect.Response[agentpb.RebootResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vz.agent.v1.Agent.Reboot is not implemented"))
}

// UserAgentClient is a client for the vz.agent.v1.UserAgent service.
type UserAgentClient interface {
	// UserExec runs a command as the logged-in user, inheriting TCC and FDA.
	UserExec(context.Context, *connect.Request[agentpb.ExecRequest]) (*connect.Response[agentpb.ExecResponse], error)
	// UserExecStream runs a command with streaming output as the logged-in user.
	UserExecStream(context.Context, *connect.Request[agentpb.ExecRequest]) (*connect.ServerStreamForClient[agentpb.ExecOutput], error)
}

// NewUserAgentClient constructs a client for the vz.agent.v1.UserAgent service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewUserAgentClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) UserAgentClient {
	baseURL = strings.TrimRight(baseURL, "/")
	userAgentMethods := agentpb.File_agent_proto.Services().ByName("UserAgent").Methods()
	return &userAgentClient{
		userExec: connect.NewClient[agentpb.ExecRequest, agentpb.ExecResponse](
			httpClient,
			baseURL+UserAgentUserExecProcedure,
			connect.WithSchema(userAgentMethods.ByName("UserExec")),
			connect.WithClientOptions(opts...),
		),
		userExecStream: connect.NewClient[agentpb.ExecRequest, agentpb.ExecOutput](
			httpClient,
			baseURL+UserAgentUserExecStreamProcedure,
			connect.WithSchema(userAgentMethods.ByName("UserExecStream")),
			connect.WithClientOptions(opts...),
		),
	}
}

// userAgentClient implements UserAgentClient.
type userAgentClient struct {
	userExec       *connect.Client[agentpb.ExecRequest, agentpb.ExecResponse]
	userExecStream *connect.Client[agentpb.ExecRequest, agentpb.ExecOutput]
}

// UserExec calls vz.agent.v1.UserAgent.UserExec.
func (c *userAgentClient) UserExec(ctx context.Context, req *connect.Request[agentpb.ExecRequest]) (*connect.Response[agentpb.ExecResponse], error) {
	return c.userExec.CallUnary(ctx, req)
}

// UserExecStream calls vz.agent.v1.UserAgent.UserExecStream.
func (c *userAgentClient) UserExecStream(ctx context.Context, req *connect.Request[agentpb.ExecRequest]) (*connect.ServerStreamForClient[agentpb.ExecOutput], error) {
	return c.userExecStream.CallServerStream(ctx, req)
}

// UserAgentHandler is an implementation of the vz.agent.v1.UserAgent service.
type UserAgentHandler interface {
	// UserExec runs a command as the logged-in user, inheriting TCC and FDA.
	UserExec(context.Context, *connect.Request[agentpb.ExecRequest]) (*connect.Response[agentpb.ExecResponse], error)
	// UserExecStream runs a command with streaming output as the logged-in user.
	UserExecStream(context.Context, *connect.Request[agentpb.ExecRequest], *connect.ServerStream[agentpb.ExecOutput]) error
}

// NewUserAgentHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewUserAgentHandler(svc UserAgentHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	userAgentMethods := agentpb.File_agent_proto.Services().ByName("UserAgent").Methods()
	userAgentUserExecHandler := connect.NewUnaryHandler(
		UserAgentUserExecProcedure,
		svc.UserExec,
		connect.WithSchema(userAgentMethods.ByName("UserExec")),
		connect.WithHandlerOptions(opts...),
	)
	userAgentUserExecStreamHandler := connect.NewServerStreamHandler(
		UserAgentUserExecStreamProcedure,
		svc.UserExecStream,
		connect.WithSchema(userAgentMethods.ByName("UserExecStream")),
		connect.WithHandlerOptions(opts...),
	)
	return "/vz.agent.v1.UserAgent/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case UserAgentUserExecProcedure:
			userAgentUserExecHandler.ServeHTTP(w, r)
		case UserAgentUserExecStreamProcedure:
			userAgentUserExecStreamHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedUserAgentHandler returns CodeUnimplemented from all methods.
type UnimplementedUserAgentHandler struct{}

func (UnimplementedUserAgentHandler) UserExec(context.Context, *connect.Request[agentpb.ExecRequest]) (*connect.Response[agentpb.ExecResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vz.agent.v1.UserAgent.UserExec is not implemented"))
}

func (UnimplementedUserAgentHandler) UserExecStream(context.Context, *connect.Request[agentpb.ExecRequest], *connect.ServerStream[agentpb.ExecOutput]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("vz.agent.v1.UserAgent.UserExecStream is not implemented"))
}
