// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: control.proto

package controlpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ControlRequest is the envelope for all control socket requests.
// Every JSON line sent to the socket is unmarshaled into this message.
// The "type" field selects the handler; the oneof carries the payload.
type ControlRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Command type string for dispatch (e.g. "key", "screenshot", "ping").
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Optional bearer token for control-socket authentication.
	AuthToken string `protobuf:"bytes,2,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	// Types that are valid to be assigned to Command:
	//
	//	*ControlRequest_Key
	//	*ControlRequest_Mouse
	//	*ControlRequest_Text
	//	*ControlRequest_Screenshot
	//	*ControlRequest_Snapshot
	//	*ControlRequest_Memory
	//	*ControlRequest_Ocr
	//	*ControlRequest_PortForward
	//	*ControlRequest_AgentExec
	//	*ControlRequest_AgentRead
	//	*ControlRequest_AgentWrite
	//	*ControlRequest_AgentShutdown
	//	*ControlRequest_AgentSshd
	//	*ControlRequest_AgentCp
	Command       isControlRequest_Command `protobuf_oneof:"command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlRequest) Reset() {
	*x = ControlRequest{}
	mi := &file_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlRequest) ProtoMessage() {}

func (x *ControlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlRequest.ProtoReflect.Descriptor instead.
func (*ControlRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{0}
}

func (x *ControlRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ControlRequest) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

func (x *ControlRequest) GetCommand() isControlRequest_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *ControlRequest) GetKey() *KeyCommand {
	if x != nil {
		if x, ok := x.Command.(*ControlRequest_Key); ok {
			return x.Key
		}
	}
	return nil
}

func (x *ControlRequest) GetMouse() *MouseCommand {
	if x != nil {
		if x, ok := x.Command.(*ControlRequest_Mouse); ok {
			return x.Mouse
		}
	}
	return nil
}

func (x *ControlRequest) GetText() *TextCommand {
	if x != nil {
		if x, ok := x.Command.(*ControlRequest_Text); ok {
			return x.Text
		}
	}
	return nil
}

func (x *ControlRequest) GetScreenshot() *ScreenshotCommand {
	if x != nil {
		if x, ok := x.Command.(*ControlRequest_Screenshot); ok {
			return x.Screenshot
		}
	}
	return nil
}

func (x *ControlRequest) GetSnapshot() *SnapshotCommand {
	if x != nil {
		if x, ok := x.Command.(*ControlRequest_Snapshot); ok {
			return x.Snapshot
		}
	}
	return nil
}

func (x *ControlRequest) GetMemory() *MemoryCommand {
	if x != nil {
		if x, ok := x.Command.(*ControlRequest_Memory); ok {
			return x.Memory
		}
	}
	return nil
}

func (x *ControlRequest) GetOcr() *OCRCommand {
	if x != nil {
		if x, ok := x.Command.(*ControlRequest_Ocr); ok {
			return x.Ocr
		}
	}
	return nil
}

func (x *ControlRequest) GetPortForward() *PortForwardCommand {
	if x != nil {
		if x, ok := x.Command.(*ControlRequest_PortForward); ok {
			return x.PortForward
		}
	}
	return nil
}

func (x *ControlRequest) GetAgentExec() *AgentExecCommand {
	if x != nil {
		if x, ok := x.Command.(*ControlRequest_AgentExec); ok {
			return x.AgentExec
		}
	}
	return nil
}

func (x *ControlRequest) GetAgentRead() *AgentFileReadCommand {
	if x != nil {
		if x, ok := x.Command.(*ControlRequest_AgentRead); ok {
			return x.AgentRead
		}
	}
	return nil
}

func (x *ControlRequest) GetAgentWrite() *AgentFileWriteCommand {
	if x != nil {
		if x, ok := x.Command.(*ControlRequest_AgentWrite); ok {
			return x.AgentWrite
		}
	}
	return nil
}

func (x *ControlRequest) GetAgentShutdown() *AgentShutdownCommand {
	if x != nil {
		if x, ok := x.Command.(*ControlRequest_AgentShutdown); ok {
			return x.AgentShutdown
		}
	}
	return nil
}

func (x *ControlRequest) GetAgentSshd() *AgentSSHDCommand {
	if x != nil {
		if x, ok := x.Command.(*ControlRequest_AgentSshd); ok {
			return x.AgentSshd
		}
	}
	return nil
}

func (x *ControlRequest) GetAgentCp() *AgentCopyCommand {
	if x != nil {
		if x, ok := x.Command.(*ControlRequest_AgentCp); ok {
			return x.AgentCp
		}
	}
	return nil
}

type isControlRequest_Command interface {
	isControlRequest_Command()
}

type ControlRequest_Key struct {
	Key *KeyCommand `protobuf:"bytes,10,opt,name=key,proto3,oneof"`
}

type ControlRequest_Mouse struct {
	Mouse *MouseCommand `protobuf:"bytes,11,opt,name=mouse,proto3,oneof"`
}

type ControlRequest_Text struct {
	Text *TextCommand `protobuf:"bytes,12,opt,name=text,proto3,oneof"`
}

type ControlRequest_Screenshot struct {
	Screenshot *ScreenshotCommand `protobuf:"bytes,13,opt,name=screenshot,proto3,oneof"`
}

type ControlRequest_Snapshot struct {
	Snapshot *SnapshotCommand `protobuf:"bytes,14,opt,name=snapshot,proto3,oneof"`
}

type ControlRequest_Memory struct {
	Memory *MemoryCommand `protobuf:"bytes,15,opt,name=memory,proto3,oneof"`
}

type ControlRequest_Ocr struct {
	Ocr *OCRCommand `protobuf:"bytes,16,opt,name=ocr,proto3,oneof"`
}

type ControlRequest_PortForward struct {
	PortForward *PortForwardCommand `protobuf:"bytes,17,opt,name=port_forward,json=portForward,proto3,oneof"`
}

type ControlRequest_AgentExec struct {
	AgentExec *AgentExecCommand `protobuf:"bytes,20,opt,name=agent_exec,json=agentExec,proto3,oneof"`
}

type ControlRequest_AgentRead struct {
	AgentRead *AgentFileReadCommand `protobuf:"bytes,21,opt,name=agent_read,json=agentRead,proto3,oneof"`
}

type ControlRequest_AgentWrite struct {
	AgentWrite *AgentFileWriteCommand `protobuf:"bytes,22,opt,name=agent_write,json=agentWrite,proto3,oneof"`
}

type ControlRequest_AgentShutdown struct {
	AgentShutdown *AgentShutdownCommand `protobuf:"bytes,23,opt,name=agent_shutdown,json=agentShutdown,proto3,oneof"`
}

type ControlRequest_AgentSshd struct {
	AgentSshd *AgentSSHDCommand `protobuf:"bytes,24,opt,name=agent_sshd,json=agentSshd,proto3,oneof"`
}

type ControlRequest_AgentCp struct {
	AgentCp *AgentCopyCommand `protobuf:"bytes,25,opt,name=agent_cp,json=agentCp,proto3,oneof"`
}

func (*ControlRequest_Key) isControlRequest_Command() {}

func (*ControlRequest_Mouse) isControlRequest_Command() {}

func (*ControlRequest_Text) isControlRequest_Command() {}

func (*ControlRequest_Screenshot) isControlRequest_Command() {}

func (*ControlRequest_Snapshot) isControlRequest_Command() {}

func (*ControlRequest_Memory) isControlRequest_Command() {}

func (*ControlRequest_Ocr) isControlRequest_Command() {}

func (*ControlRequest_PortForward) isControlRequest_Command() {}

func (*ControlRequest_AgentExec) isControlRequest_Command() {}

func (*ControlRequest_AgentRead) isControlRequest_Command() {}

func (*ControlRequest_AgentWrite) isControlRequest_Command() {}

func (*ControlRequest_AgentShutdown) isControlRequest_Command() {}

func (*ControlRequest_AgentSshd) isControlRequest_Command() {}

func (*ControlRequest_AgentCp) isControlRequest_Command() {}

// ControlResponse is the envelope for all control socket responses.
// The "data" field (3) is kept for backward compatibility. New clients
// should read from the typed "result" oneof instead.
type ControlResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Success bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error   string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// Legacy: opaque string carrying base64 images, JSON objects, or plain text.
	Data string `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	// Typed response payload. New clients should prefer these fields.
	//
	// Types that are valid to be assigned to Result:
	//
	//	*ControlResponse_Status
	//	*ControlResponse_Capabilities
	//	*ControlResponse_ScreenshotResult
	//	*ControlResponse_Empty
	//	*ControlResponse_SnapshotList
	//	*ControlResponse_SnapshotAction
	//	*ControlResponse_Message
	//	*ControlResponse_NetworkInfo
	//	*ControlResponse_MemoryInfo
	//	*ControlResponse_AgentExecResult
	//	*ControlResponse_AgentFile
	//	*ControlResponse_AgentInfo
	//	*ControlResponse_AgentPing
	//	*ControlResponse_OcrText
	//	*ControlResponse_ScreenDetection
	Result        isControlResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlResponse) Reset() {
	*x = ControlResponse{}
	mi := &file_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlResponse) ProtoMessage() {}

func (x *ControlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlResponse.ProtoReflect.Descriptor instead.
func (*ControlResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{1}
}

func (x *ControlResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ControlResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ControlResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *ControlResponse) GetResult() isControlResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ControlResponse) GetStatus() *StatusResponse {
	if x != nil {
		if x, ok := x.Result.(*ControlResponse_Status); ok {
			return x.Status
		}
	}
	return nil
}

func (x *ControlResponse) GetCapabilities() *CapabilitiesResponse {
	if x != nil {
		if x, ok := x.Result.(*ControlResponse_Capabilities); ok {
			return x.Capabilities
		}
	}
	return nil
}

func (x *ControlResponse) GetScreenshotResult() *ScreenshotResponse {
	if x != nil {
		if x, ok := x.Result.(*ControlResponse_ScreenshotResult); ok {
			return x.ScreenshotResult
		}
	}
	return nil
}

func (x *ControlResponse) GetEmpty() *EmptyResponse {
	if x != nil {
		if x, ok := x.Result.(*ControlResponse_Empty); ok {
			return x.Empty
		}
	}
	return nil
}

func (x *ControlResponse) GetSnapshotList() *SnapshotListResponse {
	if x != nil {
		if x, ok := x.Result.(*ControlResponse_SnapshotList); ok {
			return x.SnapshotList
		}
	}
	return nil
}

func (x *ControlResponse) GetSnapshotAction() *SnapshotActionResponse {
	if x != nil {
		if x, ok := x.Result.(*ControlResponse_SnapshotAction); ok {
			return x.SnapshotAction
		}
	}
	return nil
}

func (x *ControlResponse) GetMessage() *MessageResponse {
	if x != nil {
		if x, ok := x.Result.(*ControlResponse_Message); ok {
			return x.Message
		}
	}
	return nil
}

func (x *ControlResponse) GetNetworkInfo() *NetworkInfoResponse {
	if x != nil {
		if x, ok := x.Result.(*ControlResponse_NetworkInfo); ok {
			return x.NetworkInfo
		}
	}
	return nil
}

func (x *ControlResponse) GetMemoryInfo() *MemoryInfoResponse {
	if x != nil {
		if x, ok := x.Result.(*ControlResponse_MemoryInfo); ok {
			return x.MemoryInfo
		}
	}
	return nil
}

func (x *ControlResponse) GetAgentExecResult() *AgentExecResponse {
	if x != nil {
		if x, ok := x.Result.(*ControlResponse_AgentExecResult); ok {
			return x.AgentExecResult
		}
	}
	return nil
}

func (x *ControlResponse) GetAgentFile() *AgentFileResponse {
	if x != nil {
		if x, ok := x.Result.(*ControlResponse_AgentFile); ok {
			return x.AgentFile
		}
	}
	return nil
}

func (x *ControlResponse) GetAgentInfo() *AgentInfoResponse {
	if x != nil {
		if x, ok := x.Result.(*ControlResponse_AgentInfo); ok {
			return x.AgentInfo
		}
	}
	return nil
}

func (x *ControlResponse) GetAgentPing() *AgentPingResponse {
	if x != nil {
		if x, ok := x.Result.(*ControlResponse_AgentPing); ok {
			return x.AgentPing
		}
	}
	return nil
}

func (x *ControlResponse) GetOcrText() *OCRTextResponse {
	if x != nil {
		if x, ok := x.Result.(*ControlResponse_OcrText); ok {
			return x.OcrText
		}
	}
	return nil
}

func (x *ControlResponse) GetScreenDetection() *ScreenDetectionResponse {
	if x != nil {
		if x, ok := x.Result.(*ControlResponse_ScreenDetection); ok {
			return x.ScreenDetection
		}
	}
	return nil
}

type isControlResponse_Result interface {
	isControlResponse_Result()
}

type ControlResponse_Status struct {
	Status *StatusResponse `protobuf:"bytes,10,opt,name=status,proto3,oneof"`
}

type ControlResponse_Capabilities struct {
	Capabilities *CapabilitiesResponse `protobuf:"bytes,11,opt,name=capabilities,proto3,oneof"`
}

type ControlResponse_ScreenshotResult struct {
	ScreenshotResult *ScreenshotResponse `protobuf:"bytes,12,opt,name=screenshot_result,json=screenshotResult,proto3,oneof"`
}

type ControlResponse_Empty struct {
	Empty *EmptyResponse `protobuf:"bytes,13,opt,name=empty,proto3,oneof"`
}

type ControlResponse_SnapshotList struct {
	SnapshotList *SnapshotListResponse `protobuf:"bytes,14,opt,name=snapshot_list,json=snapshotList,proto3,oneof"`
}

type ControlResponse_SnapshotAction struct {
	SnapshotAction *SnapshotActionResponse `protobuf:"bytes,15,opt,name=snapshot_action,json=snapshotAction,proto3,oneof"`
}

type ControlResponse_Message struct {
	Message *MessageResponse `protobuf:"bytes,16,opt,name=message,proto3,oneof"`
}

type ControlResponse_NetworkInfo struct {
	NetworkInfo *NetworkInfoResponse `protobuf:"bytes,17,opt,name=network_info,json=networkInfo,proto3,oneof"`
}

type ControlResponse_MemoryInfo struct {
	MemoryInfo *MemoryInfoResponse `protobuf:"bytes,18,opt,name=memory_info,json=memoryInfo,proto3,oneof"`
}

type ControlResponse_AgentExecResult struct {
	AgentExecResult *AgentExecResponse `protobuf:"bytes,20,opt,name=agent_exec_result,json=agentExecResult,proto3,oneof"`
}

type ControlResponse_AgentFile struct {
	AgentFile *AgentFileResponse `protobuf:"bytes,21,opt,name=agent_file,json=agentFile,proto3,oneof"`
}

type ControlResponse_AgentInfo struct {
	AgentInfo *AgentInfoResponse `protobuf:"bytes,22,opt,name=agent_info,json=agentInfo,proto3,oneof"`
}

type ControlResponse_AgentPing struct {
	AgentPing *AgentPingResponse `protobuf:"bytes,23,opt,name=agent_ping,json=agentPing,proto3,oneof"`
}

type ControlResponse_OcrText struct {
	OcrText *OCRTextResponse `protobuf:"bytes,24,opt,name=ocr_text,json=ocrText,proto3,oneof"`
}

type ControlResponse_ScreenDetection struct {
	ScreenDetection *ScreenDetectionResponse `protobuf:"bytes,25,opt,name=screen_detection,json=screenDetection,proto3,oneof"`
}

func (*ControlResponse_Status) isControlResponse_Result() {}

func (*ControlResponse_Capabilities) isControlResponse_Result() {}

func (*ControlResponse_ScreenshotResult) isControlResponse_Result() {}

func (*ControlResponse_Empty) isControlResponse_Result() {}

func (*ControlResponse_SnapshotList) isControlResponse_Result() {}

func (*ControlResponse_SnapshotAction) isControlResponse_Result() {}

func (*ControlResponse_Message) isControlResponse_Result() {}

func (*ControlResponse_NetworkInfo) isControlResponse_Result() {}

func (*ControlResponse_MemoryInfo) isControlResponse_Result() {}

func (*ControlResponse_AgentExecResult) isControlResponse_Result() {}

func (*ControlResponse_AgentFile) isControlResponse_Result() {}

func (*ControlResponse_AgentInfo) isControlResponse_Result() {}

func (*ControlResponse_AgentPing) isControlResponse_Result() {}

func (*ControlResponse_OcrText) isControlResponse_Result() {}

func (*ControlResponse_ScreenDetection) isControlResponse_Result() {}

// KeyCommand sends a keyboard event to the VM.
type KeyCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyCode       uint32                 `protobuf:"varint,1,opt,name=key_code,json=keyCode,proto3" json:"key_code,omitempty"`
	Character     string                 `protobuf:"bytes,2,opt,name=character,proto3" json:"character,omitempty"`
	Modifiers     uint32                 `protobuf:"varint,3,opt,name=modifiers,proto3" json:"modifiers,omitempty"`
	KeyDown       bool                   `protobuf:"varint,4,opt,name=key_down,json=keyDown,proto3" json:"key_down,omitempty"`
	UseCgEvent    bool                   `protobuf:"varint,5,opt,name=use_cg_event,json=useCgEvent,proto3" json:"use_cg_event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyCommand) Reset() {
	*x = KeyCommand{}
	mi := &file_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyCommand) ProtoMessage() {}

func (x *KeyCommand) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyCommand.ProtoReflect.Descriptor instead.
func (*KeyCommand) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{2}
}

func (x *KeyCommand) GetKeyCode() uint32 {
	if x != nil {
		return x.KeyCode
	}
	return 0
}

func (x *KeyCommand) GetCharacter() string {
	if x != nil {
		return x.Character
	}
	return ""
}

func (x *KeyCommand) GetModifiers() uint32 {
	if x != nil {
		return x.Modifiers
	}
	return 0
}

func (x *KeyCommand) GetKeyDown() bool {
	if x != nil {
		return x.KeyDown
	}
	return false
}

func (x *KeyCommand) GetUseCgEvent() bool {
	if x != nil {
		return x.UseCgEvent
	}
	return false
}

// MouseCommand sends a mouse event to the VM.
type MouseCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	Button        int32                  `protobuf:"varint,3,opt,name=button,proto3" json:"button,omitempty"`
	Action        string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	ScrollX       float64                `protobuf:"fixed64,5,opt,name=scroll_x,json=scrollX,proto3" json:"scroll_x,omitempty"`
	ScrollY       float64                `protobuf:"fixed64,6,opt,name=scroll_y,json=scrollY,proto3" json:"scroll_y,omitempty"`
	Absolute      bool                   `protobuf:"varint,7,opt,name=absolute,proto3" json:"absolute,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MouseCommand) Reset() {
	*x = MouseCommand{}
	mi := &file_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MouseCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MouseCommand) ProtoMessage() {}

func (x *MouseCommand) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MouseCommand.ProtoReflect.Descriptor instead.
func (*MouseCommand) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{3}
}

func (x *MouseCommand) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *MouseCommand) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *MouseCommand) GetButton() int32 {
	if x != nil {
		return x.Button
	}
	return 0
}

func (x *MouseCommand) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *MouseCommand) GetScrollX() float64 {
	if x != nil {
		return x.ScrollX
	}
	return 0
}

func (x *MouseCommand) GetScrollY() float64 {
	if x != nil {
		return x.ScrollY
	}
	return 0
}

func (x *MouseCommand) GetAbsolute() bool {
	if x != nil {
		return x.Absolute
	}
	return false
}

// TextCommand types a string of text character by character.
type TextCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextCommand) Reset() {
	*x = TextCommand{}
	mi := &file_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextCommand) ProtoMessage() {}

func (x *TextCommand) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextCommand.ProtoReflect.Descriptor instead.
func (*TextCommand) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{4}
}

func (x *TextCommand) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// ScreenshotCommand captures the VM display.
type ScreenshotCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Diff          bool                   `protobuf:"varint,1,opt,name=diff,proto3" json:"diff,omitempty"`
	Scale         float64                `protobuf:"fixed64,2,opt,name=scale,proto3" json:"scale,omitempty"`
	Quality       int32                  `protobuf:"varint,3,opt,name=quality,proto3" json:"quality,omitempty"`
	Format        string                 `protobuf:"bytes,4,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScreenshotCommand) Reset() {
	*x = ScreenshotCommand{}
	mi := &file_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreenshotCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreenshotCommand) ProtoMessage() {}

func (x *ScreenshotCommand) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreenshotCommand.ProtoReflect.Descriptor instead.
func (*ScreenshotCommand) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{5}
}

func (x *ScreenshotCommand) GetDiff() bool {
	if x != nil {
		return x.Diff
	}
	return false
}

func (x *ScreenshotCommand) GetScale() float64 {
	if x != nil {
		return x.Scale
	}
	return 0
}

func (x *ScreenshotCommand) GetQuality() int32 {
	if x != nil {
		return x.Quality
	}
	return 0
}

func (x *ScreenshotCommand) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

// SnapshotCommand manages VM state snapshots.
type SnapshotCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotCommand) Reset() {
	*x = SnapshotCommand{}
	mi := &file_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotCommand) ProtoMessage() {}

func (x *SnapshotCommand) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotCommand.ProtoReflect.Descriptor instead.
func (*SnapshotCommand) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{6}
}

func (x *SnapshotCommand) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *SnapshotCommand) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// MemoryCommand manages runtime memory balloon.
type MemoryCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	SizeGb        float64                `protobuf:"fixed64,2,opt,name=size_gb,json=sizeGb,proto3" json:"size_gb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryCommand) Reset() {
	*x = MemoryCommand{}
	mi := &file_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryCommand) ProtoMessage() {}

func (x *MemoryCommand) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryCommand.ProtoReflect.Descriptor instead.
func (*MemoryCommand) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{7}
}

func (x *MemoryCommand) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *MemoryCommand) GetSizeGb() float64 {
	if x != nil {
		return x.SizeGb
	}
	return 0
}

// OCRCommand performs OCR operations on the VM display.
type OCRCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Action: "click", "wait", "gone", "all-text", "detect-page", "detect-screen"
	Action string `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	// Target text for click/wait/gone operations.
	Text string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	// Timeout as a Go duration string (e.g. "10s", "1m").
	Timeout       string `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OCRCommand) Reset() {
	*x = OCRCommand{}
	mi := &file_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OCRCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OCRCommand) ProtoMessage() {}

func (x *OCRCommand) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OCRCommand.ProtoReflect.Descriptor instead.
func (*OCRCommand) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{8}
}

func (x *OCRCommand) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *OCRCommand) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *OCRCommand) GetTimeout() string {
	if x != nil {
		return x.Timeout
	}
	return ""
}

// PortForwardCommand manages host TCP -> guest vsock port forwarding.
type PortForwardCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Action: "start", "stop", "list"
	Action string `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	// Host TCP port to listen on.
	HostPort uint32 `protobuf:"varint,2,opt,name=host_port,json=hostPort,proto3" json:"host_port,omitempty"`
	// Guest vsock port to forward to.
	GuestPort     uint32 `protobuf:"varint,3,opt,name=guest_port,json=guestPort,proto3" json:"guest_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortForwardCommand) Reset() {
	*x = PortForwardCommand{}
	mi := &file_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortForwardCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortForwardCommand) ProtoMessage() {}

func (x *PortForwardCommand) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortForwardCommand.ProtoReflect.Descriptor instead.
func (*PortForwardCommand) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{9}
}

func (x *PortForwardCommand) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *PortForwardCommand) GetHostPort() uint32 {
	if x != nil {
		return x.HostPort
	}
	return 0
}

func (x *PortForwardCommand) GetGuestPort() uint32 {
	if x != nil {
		return x.GuestPort
	}
	return 0
}

// AgentExecCommand runs a command inside the guest.
type AgentExecCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Args          []string               `protobuf:"bytes,1,rep,name=args,proto3" json:"args,omitempty"`
	Env           map[string]string      `protobuf:"bytes,2,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	WorkingDir    string                 `protobuf:"bytes,3,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentExecCommand) Reset() {
	*x = AgentExecCommand{}
	mi := &file_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentExecCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentExecCommand) ProtoMessage() {}

func (x *AgentExecCommand) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentExecCommand.ProtoReflect.Descriptor instead.
func (*AgentExecCommand) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{10}
}

func (x *AgentExecCommand) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *AgentExecCommand) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *AgentExecCommand) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

// AgentFileReadCommand reads a file from the guest.
type AgentFileReadCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentFileReadCommand) Reset() {
	*x = AgentFileReadCommand{}
	mi := &file_control_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentFileReadCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentFileReadCommand) ProtoMessage() {}

func (x *AgentFileReadCommand) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentFileReadCommand.ProtoReflect.Descriptor instead.
func (*AgentFileReadCommand) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{11}
}

func (x *AgentFileReadCommand) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// AgentFileWriteCommand writes a file to the guest.
type AgentFileWriteCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Data          string                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Mode          uint32                 `protobuf:"varint,3,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentFileWriteCommand) Reset() {
	*x = AgentFileWriteCommand{}
	mi := &file_control_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentFileWriteCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentFileWriteCommand) ProtoMessage() {}

func (x *AgentFileWriteCommand) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentFileWriteCommand.ProtoReflect.Descriptor instead.
func (*AgentFileWriteCommand) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{12}
}

func (x *AgentFileWriteCommand) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *AgentFileWriteCommand) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *AgentFileWriteCommand) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

// AgentShutdownCommand triggers a graceful shutdown.
type AgentShutdownCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Force         bool                   `protobuf:"varint,1,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentShutdownCommand) Reset() {
	*x = AgentShutdownCommand{}
	mi := &file_control_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentShutdownCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentShutdownCommand) ProtoMessage() {}

func (x *AgentShutdownCommand) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentShutdownCommand.ProtoReflect.Descriptor instead.
func (*AgentShutdownCommand) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{13}
}

func (x *AgentShutdownCommand) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

// AgentSSHDCommand manages sshd via systemsetup.
type AgentSSHDCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentSSHDCommand) Reset() {
	*x = AgentSSHDCommand{}
	mi := &file_control_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentSSHDCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentSSHDCommand) ProtoMessage() {}

func (x *AgentSSHDCommand) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentSSHDCommand.ProtoReflect.Descriptor instead.
func (*AgentSSHDCommand) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{14}
}

func (x *AgentSSHDCommand) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

// AgentCopyCommand copies files between host and guest using streaming gRPC.
// Direction is determined by the presence of host_path and guest_path:
//   - host_path set + guest_path set: copy host→guest (to_guest=true) or guest→host (to_guest=false)
type AgentCopyCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostPath      string                 `protobuf:"bytes,1,opt,name=host_path,json=hostPath,proto3" json:"host_path,omitempty"`
	GuestPath     string                 `protobuf:"bytes,2,opt,name=guest_path,json=guestPath,proto3" json:"guest_path,omitempty"`
	ToGuest       bool                   `protobuf:"varint,3,opt,name=to_guest,json=toGuest,proto3" json:"to_guest,omitempty"`
	Mode          uint32                 `protobuf:"varint,4,opt,name=mode,proto3" json:"mode,omitempty"`
	Overwrite     bool                   `protobuf:"varint,5,opt,name=overwrite,proto3" json:"overwrite,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentCopyCommand) Reset() {
	*x = AgentCopyCommand{}
	mi := &file_control_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentCopyCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentCopyCommand) ProtoMessage() {}

func (x *AgentCopyCommand) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentCopyCommand.ProtoReflect.Descriptor instead.
func (*AgentCopyCommand) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{15}
}

func (x *AgentCopyCommand) GetHostPath() string {
	if x != nil {
		return x.HostPath
	}
	return ""
}

func (x *AgentCopyCommand) GetGuestPath() string {
	if x != nil {
		return x.GuestPath
	}
	return ""
}

func (x *AgentCopyCommand) GetToGuest() bool {
	if x != nil {
		return x.ToGuest
	}
	return false
}

func (x *AgentCopyCommand) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *AgentCopyCommand) GetOverwrite() bool {
	if x != nil {
		return x.Overwrite
	}
	return false
}

// StatusResponse contains VM state and available operations.
type StatusResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	State          string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	CanPause       bool                   `protobuf:"varint,2,opt,name=can_pause,json=canPause,proto3" json:"can_pause,omitempty"`
	CanResume      bool                   `protobuf:"varint,3,opt,name=can_resume,json=canResume,proto3" json:"can_resume,omitempty"`
	CanStop        bool                   `protobuf:"varint,4,opt,name=can_stop,json=canStop,proto3" json:"can_stop,omitempty"`
	CanRequestStop bool                   `protobuf:"varint,5,opt,name=can_request_stop,json=canRequestStop,proto3" json:"can_request_stop,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_control_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{16}
}

func (x *StatusResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *StatusResponse) GetCanPause() bool {
	if x != nil {
		return x.CanPause
	}
	return false
}

func (x *StatusResponse) GetCanResume() bool {
	if x != nil {
		return x.CanResume
	}
	return false
}

func (x *StatusResponse) GetCanStop() bool {
	if x != nil {
		return x.CanStop
	}
	return false
}

func (x *StatusResponse) GetCanRequestStop() bool {
	if x != nil {
		return x.CanRequestStop
	}
	return false
}

// CapabilitiesResponse describes the control protocol capabilities.
type CapabilitiesResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion string                 `protobuf:"bytes,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	Encoding        string                 `protobuf:"bytes,2,opt,name=encoding,proto3" json:"encoding,omitempty"`
	Commands        []string               `protobuf:"bytes,3,rep,name=commands,proto3" json:"commands,omitempty"`
	Features        map[string]bool        `protobuf:"bytes,4,rep,name=features,proto3" json:"features,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	AuthRequired    bool                   `protobuf:"varint,5,opt,name=auth_required,json=authRequired,proto3" json:"auth_required,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CapabilitiesResponse) Reset() {
	*x = CapabilitiesResponse{}
	mi := &file_control_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesResponse) ProtoMessage() {}

func (x *CapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*CapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{17}
}

func (x *CapabilitiesResponse) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *CapabilitiesResponse) GetEncoding() string {
	if x != nil {
		return x.Encoding
	}
	return ""
}

func (x *CapabilitiesResponse) GetCommands() []string {
	if x != nil {
		return x.Commands
	}
	return nil
}

func (x *CapabilitiesResponse) GetFeatures() map[string]bool {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *CapabilitiesResponse) GetAuthRequired() bool {
	if x != nil {
		return x.AuthRequired
	}
	return false
}

// ScreenshotResponse contains a captured VM display image.
type ScreenshotResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raw image bytes (PNG or JPEG). Not base64-encoded.
	ImageData []byte `protobuf:"bytes,1,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"`
	// Image format: "png" or "jpeg".
	Format string `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	// Image dimensions after scaling.
	Width         int32 `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32 `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScreenshotResponse) Reset() {
	*x = ScreenshotResponse{}
	mi := &file_control_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreenshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreenshotResponse) ProtoMessage() {}

func (x *ScreenshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreenshotResponse.ProtoReflect.Descriptor instead.
func (*ScreenshotResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{18}
}

func (x *ScreenshotResponse) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

func (x *ScreenshotResponse) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *ScreenshotResponse) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ScreenshotResponse) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

// EmptyResponse is used for commands that have no meaningful payload.
type EmptyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyResponse) Reset() {
	*x = EmptyResponse{}
	mi := &file_control_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyResponse) ProtoMessage() {}

func (x *EmptyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyResponse.ProtoReflect.Descriptor instead.
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{19}
}

// SnapshotListResponse wraps a list of snapshot metadata.
type SnapshotListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshots     []*SnapshotInfo        `protobuf:"bytes,1,rep,name=snapshots,proto3" json:"snapshots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotListResponse) Reset() {
	*x = SnapshotListResponse{}
	mi := &file_control_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotListResponse) ProtoMessage() {}

func (x *SnapshotListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotListResponse.ProtoReflect.Descriptor instead.
func (*SnapshotListResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{20}
}

func (x *SnapshotListResponse) GetSnapshots() []*SnapshotInfo {
	if x != nil {
		return x.Snapshots
	}
	return nil
}

// SnapshotActionResponse carries the result of a snapshot save/restore/delete.
type SnapshotActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotActionResponse) Reset() {
	*x = SnapshotActionResponse{}
	mi := &file_control_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotActionResponse) ProtoMessage() {}

func (x *SnapshotActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotActionResponse.ProtoReflect.Descriptor instead.
func (*SnapshotActionResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{21}
}

func (x *SnapshotActionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// MessageResponse carries a simple string message.
type MessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageResponse) Reset() {
	*x = MessageResponse{}
	mi := &file_control_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageResponse) ProtoMessage() {}

func (x *MessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageResponse.ProtoReflect.Descriptor instead.
func (*MessageResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{22}
}

func (x *MessageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// MemoryInfoResponse wraps memory info for the typed oneof.
type MemoryInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *MemoryInfo            `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryInfoResponse) Reset() {
	*x = MemoryInfoResponse{}
	mi := &file_control_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryInfoResponse) ProtoMessage() {}

func (x *MemoryInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryInfoResponse.ProtoReflect.Descriptor instead.
func (*MemoryInfoResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{23}
}

func (x *MemoryInfoResponse) GetInfo() *MemoryInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

// NetworkInfoResponse contains VM network configuration.
type NetworkInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MacAddress    string                 `protobuf:"bytes,1,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	GuestIp       string                 `protobuf:"bytes,2,opt,name=guest_ip,json=guestIp,proto3" json:"guest_ip,omitempty"`
	Mode          string                 `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkInfoResponse) Reset() {
	*x = NetworkInfoResponse{}
	mi := &file_control_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkInfoResponse) ProtoMessage() {}

func (x *NetworkInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkInfoResponse.ProtoReflect.Descriptor instead.
func (*NetworkInfoResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{24}
}

func (x *NetworkInfoResponse) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *NetworkInfoResponse) GetGuestIp() string {
	if x != nil {
		return x.GuestIp
	}
	return ""
}

func (x *NetworkInfoResponse) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

// MemoryInfo contains information about VM memory configuration.
type MemoryInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ConfiguredGb     float64                `protobuf:"fixed64,1,opt,name=configured_gb,json=configuredGb,proto3" json:"configured_gb,omitempty"`
	TargetGb         float64                `protobuf:"fixed64,2,opt,name=target_gb,json=targetGb,proto3" json:"target_gb,omitempty"`
	MinimumAllowedMb uint64                 `protobuf:"varint,3,opt,name=minimum_allowed_mb,json=minimumAllowedMb,proto3" json:"minimum_allowed_mb,omitempty"`
	HasBalloon       bool                   `protobuf:"varint,4,opt,name=has_balloon,json=hasBalloon,proto3" json:"has_balloon,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MemoryInfo) Reset() {
	*x = MemoryInfo{}
	mi := &file_control_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryInfo) ProtoMessage() {}

func (x *MemoryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryInfo.ProtoReflect.Descriptor instead.
func (*MemoryInfo) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{25}
}

func (x *MemoryInfo) GetConfiguredGb() float64 {
	if x != nil {
		return x.ConfiguredGb
	}
	return 0
}

func (x *MemoryInfo) GetTargetGb() float64 {
	if x != nil {
		return x.TargetGb
	}
	return 0
}

func (x *MemoryInfo) GetMinimumAllowedMb() uint64 {
	if x != nil {
		return x.MinimumAllowedMb
	}
	return 0
}

func (x *MemoryInfo) GetHasBalloon() bool {
	if x != nil {
		return x.HasBalloon
	}
	return false
}

// SnapshotInfo contains metadata about a saved snapshot.
type SnapshotInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Created       string                 `protobuf:"bytes,2,opt,name=created,proto3" json:"created,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	VmState       string                 `protobuf:"bytes,4,opt,name=vm_state,json=vmState,proto3" json:"vm_state,omitempty"`
	FilePath      string                 `protobuf:"bytes,5,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotInfo) Reset() {
	*x = SnapshotInfo{}
	mi := &file_control_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotInfo) ProtoMessage() {}

func (x *SnapshotInfo) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotInfo.ProtoReflect.Descriptor instead.
func (*SnapshotInfo) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{26}
}

func (x *SnapshotInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SnapshotInfo) GetCreated() string {
	if x != nil {
		return x.Created
	}
	return ""
}

func (x *SnapshotInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *SnapshotInfo) GetVmState() string {
	if x != nil {
		return x.VmState
	}
	return ""
}

func (x *SnapshotInfo) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

// AgentExecResponse contains the result of an agent exec command.
type AgentExecResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ExitCode        int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Stdout          string                 `protobuf:"bytes,2,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr          string                 `protobuf:"bytes,3,opt,name=stderr,proto3" json:"stderr,omitempty"`
	DurationSeconds float64                `protobuf:"fixed64,4,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AgentExecResponse) Reset() {
	*x = AgentExecResponse{}
	mi := &file_control_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentExecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentExecResponse) ProtoMessage() {}

func (x *AgentExecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentExecResponse.ProtoReflect.Descriptor instead.
func (*AgentExecResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{27}
}

func (x *AgentExecResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *AgentExecResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *AgentExecResponse) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *AgentExecResponse) GetDurationSeconds() float64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

// AgentFileResponse contains the result of an agent file operation.
type AgentFileResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raw file data (for reads). Not base64-encoded.
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// Human-readable message (for writes, copies).
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentFileResponse) Reset() {
	*x = AgentFileResponse{}
	mi := &file_control_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentFileResponse) ProtoMessage() {}

func (x *AgentFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentFileResponse.ProtoReflect.Descriptor instead.
func (*AgentFileResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{28}
}

func (x *AgentFileResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AgentFileResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// AgentInfoResponse contains guest system information.
type AgentInfoResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Hostname string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os       string                 `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"`
	Arch     string                 `protobuf:"bytes,3,opt,name=arch,proto3" json:"arch,omitempty"`
	Version  string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	// Opaque JSON payload for extensibility.
	RawJson       string `protobuf:"bytes,5,opt,name=raw_json,json=rawJson,proto3" json:"raw_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentInfoResponse) Reset() {
	*x = AgentInfoResponse{}
	mi := &file_control_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInfoResponse) ProtoMessage() {}

func (x *AgentInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInfoResponse.ProtoReflect.Descriptor instead.
func (*AgentInfoResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{29}
}

func (x *AgentInfoResponse) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *AgentInfoResponse) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *AgentInfoResponse) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *AgentInfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AgentInfoResponse) GetRawJson() string {
	if x != nil {
		return x.RawJson
	}
	return ""
}

// AgentPingResponse contains the agent version.
type AgentPingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentPingResponse) Reset() {
	*x = AgentPingResponse{}
	mi := &file_control_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentPingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentPingResponse) ProtoMessage() {}

func (x *AgentPingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentPingResponse.ProtoReflect.Descriptor instead.
func (*AgentPingResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{30}
}

func (x *AgentPingResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// OCRTextResponse contains OCR results from the VM display.
type OCRTextResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Full recognized text (for all-text action).
	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	// Individual text matches with bounding boxes.
	Matches       []*OCRMatch `protobuf:"bytes,2,rep,name=matches,proto3" json:"matches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OCRTextResponse) Reset() {
	*x = OCRTextResponse{}
	mi := &file_control_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OCRTextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OCRTextResponse) ProtoMessage() {}

func (x *OCRTextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OCRTextResponse.ProtoReflect.Descriptor instead.
func (*OCRTextResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{31}
}

func (x *OCRTextResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *OCRTextResponse) GetMatches() []*OCRMatch {
	if x != nil {
		return x.Matches
	}
	return nil
}

// OCRMatch represents a single OCR text match with its location.
type OCRMatch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Text  string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	// Normalized coordinates (0-1 range, top-left origin).
	X             float64 `protobuf:"fixed64,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64 `protobuf:"fixed64,3,opt,name=y,proto3" json:"y,omitempty"`
	Width         float64 `protobuf:"fixed64,4,opt,name=width,proto3" json:"width,omitempty"`
	Height        float64 `protobuf:"fixed64,5,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OCRMatch) Reset() {
	*x = OCRMatch{}
	mi := &file_control_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OCRMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OCRMatch) ProtoMessage() {}

func (x *OCRMatch) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OCRMatch.ProtoReflect.Descriptor instead.
func (*OCRMatch) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{32}
}

func (x *OCRMatch) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *OCRMatch) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *OCRMatch) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *OCRMatch) GetWidth() float64 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *OCRMatch) GetHeight() float64 {
	if x != nil {
		return x.Height
	}
	return 0
}

// ScreenDetectionResponse contains the detected screen state.
type ScreenDetectionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Detected state: "black", "apple-logo", "setup-assistant", "login", "desktop", "unknown"
	State         string `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScreenDetectionResponse) Reset() {
	*x = ScreenDetectionResponse{}
	mi := &file_control_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreenDetectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreenDetectionResponse) ProtoMessage() {}

func (x *ScreenDetectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreenDetectionResponse.ProtoReflect.Descriptor instead.
func (*ScreenDetectionResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{33}
}

func (x *ScreenDetectionResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

var File_control_proto protoreflect.FileDescriptor

const file_control_proto_rawDesc = "" +
	"\n" +
	"\rcontrol.proto\x12\rvz.control.v1\"\xb4\a\n" +
	"\x0eControlRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x02 \x01(\tR\tauthToken\x12-\n" +
	"\x03key\x18\n" +
	" \x01(\v2\x19.vz.control.v1.KeyCommandH\x00R\x03key\x123\n" +
	"\x05mouse\x18\v \x01(\v2\x1b.vz.control.v1.MouseCommandH\x00R\x05mouse\x120\n" +
	"\x04text\x18\f \x01(\v2\x1a.vz.control.v1.TextCommandH\x00R\x04text\x12B\n" +
	"\n" +
	"screenshot\x18\r \x01(\v2 .vz.control.v1.ScreenshotCommandH\x00R\n" +
	"screenshot\x12<\n" +
	"\bsnapshot\x18\x0e \x01(\v2\x1e.vz.control.v1.SnapshotCommandH\x00R\bsnapshot\x126\n" +
	"\x06memory\x18\x0f \x01(\v2\x1c.vz.control.v1.MemoryCommandH\x00R\x06memory\x12-\n" +
	"\x03ocr\x18\x10 \x01(\v2\x19.vz.control.v1.OCRCommandH\x00R\x03ocr\x12F\n" +
	"\fport_forward\x18\x11 \x01(\v2!.vz.control.v1.PortForwardCommandH\x00R\vportForward\x12@\n" +
	"\n" +
	"agent_exec\x18\x14 \x01(\v2\x1f.vz.control.v1.AgentExecCommandH\x00R\tagentExec\x12D\n" +
	"\n" +
	"agent_read\x18\x15 \x01(\v2#.vz.control.v1.AgentFileReadCommandH\x00R\tagentRead\x12G\n" +
	"\vagent_write\x18\x16 \x01(\v2$.vz.control.v1.AgentFileWriteCommandH\x00R\n" +
	"agentWrite\x12L\n" +
	"\x0eagent_shutdown\x18\x17 \x01(\v2#.vz.control.v1.AgentShutdownCommandH\x00R\ragentShutdown\x12@\n" +
	"\n" +
	"agent_sshd\x18\x18 \x01(\v2\x1f.vz.control.v1.AgentSSHDCommandH\x00R\tagentSshd\x12<\n" +
	"\bagent_cp\x18\x19 \x01(\v2\x1f.vz.control.v1.AgentCopyCommandH\x00R\aagentCpB\t\n" +
	"\acommand\"\xff\b\n" +
	"\x0fControlResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data\x127\n" +
	"\x06status\x18\n" +
	" \x01(\v2\x1d.vz.control.v1.StatusResponseH\x00R\x06status\x12I\n" +
	"\fcapabilities\x18\v \x01(\v2#.vz.control.v1.CapabilitiesResponseH\x00R\fcapabilities\x12P\n" +
	"\x11screenshot_result\x18\f \x01(\v2!.vz.control.v1.ScreenshotResponseH\x00R\x10screenshotResult\x124\n" +
	"\x05empty\x18\r \x01(\v2\x1c.vz.control.v1.EmptyResponseH\x00R\x05empty\x12J\n" +
	"\rsnapshot_list\x18\x0e \x01(\v2#.vz.control.v1.SnapshotListResponseH\x00R\fsnapshotList\x12P\n" +
	"\x0fsnapshot_action\x18\x0f \x01(\v2%.vz.control.v1.SnapshotActionResponseH\x00R\x0esnapshotAction\x12:\n" +
	"\amessage\x18\x10 \x01(\v2\x1e.vz.control.v1.MessageResponseH\x00R\amessage\x12G\n" +
	"\fnetwork_info\x18\x11 \x01(\v2\".vz.control.v1.NetworkInfoResponseH\x00R\vnetworkInfo\x12D\n" +
	"\vmemory_info\x18\x12 \x01(\v2!.vz.control.v1.MemoryInfoResponseH\x00R\n" +
	"memoryInfo\x12N\n" +
	"\x11agent_exec_result\x18\x14 \x01(\v2 .vz.control.v1.AgentExecResponseH\x00R\x0fagentExecResult\x12A\n" +
	"\n" +
	"agent_file\x18\x15 \x01(\v2 .vz.control.v1.AgentFileResponseH\x00R\tagentFile\x12A\n" +
	"\n" +
	"agent_info\x18\x16 \x01(\v2 .vz.control.v1.AgentInfoResponseH\x00R\tagentInfo\x12A\n" +
	"\n" +
	"agent_ping\x18\x17 \x01(\v2 .vz.control.v1.AgentPingResponseH\x00R\tagentPing\x12;\n" +
	"\bocr_text\x18\x18 \x01(\v2\x1e.vz.control.v1.OCRTextResponseH\x00R\aocrText\x12S\n" +
	"\x10screen_detection\x18\x19 \x01(\v2&.vz.control.v1.ScreenDetectionResponseH\x00R\x0fscreenDetectionB\b\n" +
	"\x06result\"\xa0\x01\n" +
	"\n" +
	"KeyCommand\x12\x19\n" +
	"\bkey_code\x18\x01 \x01(\rR\akeyCode\x12\x1c\n" +
	"\tcharacter\x18\x02 \x01(\tR\tcharacter\x12\x1c\n" +
	"\tmodifiers\x18\x03 \x01(\rR\tmodifiers\x12\x19\n" +
	"\bkey_down\x18\x04 \x01(\bR\akeyDown\x12 \n" +
	"\fuse_cg_event\x18\x05 \x01(\bR\n" +
	"useCgEvent\"\xac\x01\n" +
	"\fMouseCommand\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\x12\x16\n" +
	"\x06button\x18\x03 \x01(\x05R\x06button\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x12\x19\n" +
	"\bscroll_x\x18\x05 \x01(\x01R\ascrollX\x12\x19\n" +
	"\bscroll_y\x18\x06 \x01(\x01R\ascrollY\x12\x1a\n" +
	"\babsolute\x18\a \x01(\bR\babsolute\"!\n" +
	"\vTextCommand\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"o\n" +
	"\x11ScreenshotCommand\x12\x12\n" +
	"\x04diff\x18\x01 \x01(\bR\x04diff\x12\x14\n" +
	"\x05scale\x18\x02 \x01(\x01R\x05scale\x12\x18\n" +
	"\aquality\x18\x03 \x01(\x05R\aquality\x12\x16\n" +
	"\x06format\x18\x04 \x01(\tR\x06format\"=\n" +
	"\x0fSnapshotCommand\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"@\n" +
	"\rMemoryCommand\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x17\n" +
	"\asize_gb\x18\x02 \x01(\x01R\x06sizeGb\"R\n" +
	"\n" +
	"OCRCommand\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x18\n" +
	"\atimeout\x18\x03 \x01(\tR\atimeout\"h\n" +
	"\x12PortForwardCommand\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x1b\n" +
	"\thost_port\x18\x02 \x01(\rR\bhostPort\x12\x1d\n" +
	"\n" +
	"guest_port\x18\x03 \x01(\rR\tguestPort\"\xbb\x01\n" +
	"\x10AgentExecCommand\x12\x12\n" +
	"\x04args\x18\x01 \x03(\tR\x04args\x12:\n" +
	"\x03env\x18\x02 \x03(\v2(.vz.control.v1.AgentExecCommand.EnvEntryR\x03env\x12\x1f\n" +
	"\vworking_dir\x18\x03 \x01(\tR\n" +
	"workingDir\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"*\n" +
	"\x14AgentFileReadCommand\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"S\n" +
	"\x15AgentFileWriteCommand\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04data\x18\x02 \x01(\tR\x04data\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\rR\x04mode\",\n" +
	"\x14AgentShutdownCommand\x12\x14\n" +
	"\x05force\x18\x01 \x01(\bR\x05force\"*\n" +
	"\x10AgentSSHDCommand\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\"\x9b\x01\n" +
	"\x10AgentCopyCommand\x12\x1b\n" +
	"\thost_path\x18\x01 \x01(\tR\bhostPath\x12\x1d\n" +
	"\n" +
	"guest_path\x18\x02 \x01(\tR\tguestPath\x12\x19\n" +
	"\bto_guest\x18\x03 \x01(\bR\atoGuest\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\rR\x04mode\x12\x1c\n" +
	"\toverwrite\x18\x05 \x01(\bR\toverwrite\"\xa7\x01\n" +
	"\x0eStatusResponse\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12\x1b\n" +
	"\tcan_pause\x18\x02 \x01(\bR\bcanPause\x12\x1d\n" +
	"\n" +
	"can_resume\x18\x03 \x01(\bR\tcanResume\x12\x19\n" +
	"\bcan_stop\x18\x04 \x01(\bR\acanStop\x12(\n" +
	"\x10can_request_stop\x18\x05 \x01(\bR\x0ecanRequestStop\"\xaa\x02\n" +
	"\x14CapabilitiesResponse\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\tR\x0fprotocolVersion\x12\x1a\n" +
	"\bencoding\x18\x02 \x01(\tR\bencoding\x12\x1a\n" +
	"\bcommands\x18\x03 \x03(\tR\bcommands\x12M\n" +
	"\bfeatures\x18\x04 \x03(\v21.vz.control.v1.CapabilitiesResponse.FeaturesEntryR\bfeatures\x12#\n" +
	"\rauth_required\x18\x05 \x01(\bR\fauthRequired\x1a;\n" +
	"\rFeaturesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\"y\n" +
	"\x12ScreenshotResponse\x12\x1d\n" +
	"\n" +
	"image_data\x18\x01 \x01(\fR\timageData\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x05R\x06height\"\x0f\n" +
	"\rEmptyResponse\"Q\n" +
	"\x14SnapshotListResponse\x129\n" +
	"\tsnapshots\x18\x01 \x03(\v2\x1b.vz.control.v1.SnapshotInfoR\tsnapshots\"2\n" +
	"\x16SnapshotActionResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"+\n" +
	"\x0fMessageResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"C\n" +
	"\x12MemoryInfoResponse\x12-\n" +
	"\x04info\x18\x01 \x01(\v2\x19.vz.control.v1.MemoryInfoR\x04info\"e\n" +
	"\x13NetworkInfoResponse\x12\x1f\n" +
	"\vmac_address\x18\x01 \x01(\tR\n" +
	"macAddress\x12\x19\n" +
	"\bguest_ip\x18\x02 \x01(\tR\aguestIp\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\tR\x04mode\"\x9d\x01\n" +
	"\n" +
	"MemoryInfo\x12#\n" +
	"\rconfigured_gb\x18\x01 \x01(\x01R\fconfiguredGb\x12\x1b\n" +
	"\ttarget_gb\x18\x02 \x01(\x01R\btargetGb\x12,\n" +
	"\x12minimum_allowed_mb\x18\x03 \x01(\x04R\x10minimumAllowedMb\x12\x1f\n" +
	"\vhas_balloon\x18\x04 \x01(\bR\n" +
	"hasBalloon\"\x88\x01\n" +
	"\fSnapshotInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acreated\x18\x02 \x01(\tR\acreated\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x19\n" +
	"\bvm_state\x18\x04 \x01(\tR\avmState\x12\x1b\n" +
	"\tfile_path\x18\x05 \x01(\tR\bfilePath\"\x8b\x01\n" +
	"\x11AgentExecResponse\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x02 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x03 \x01(\tR\x06stderr\x12)\n" +
	"\x10duration_seconds\x18\x04 \x01(\x01R\x0fdurationSeconds\"A\n" +
	"\x11AgentFileResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x88\x01\n" +
	"\x11AgentInfoResponse\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x02 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x03 \x01(\tR\x04arch\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x19\n" +
	"\braw_json\x18\x05 \x01(\tR\arawJson\"-\n" +
	"\x11AgentPingResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\"X\n" +
	"\x0fOCRTextResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x121\n" +
	"\amatches\x18\x02 \x03(\v2\x17.vz.control.v1.OCRMatchR\amatches\"h\n" +
	"\bOCRMatch\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\f\n" +
	"\x01x\x18\x02 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x01R\x01y\x12\x14\n" +
	"\x05width\x18\x04 \x01(\x01R\x05width\x12\x16\n" +
	"\x06height\x18\x05 \x01(\x01R\x06height\"/\n" +
	"\x17ScreenDetectionResponse\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05stateB6Z'github.com/tmc/vz-macos/proto/controlpb\xba\x02\n" +
	"VZControl_b\x06proto3"

var (
	file_control_proto_rawDescOnce sync.Once
	file_control_proto_rawDescData []byte
)

func file_control_proto_rawDescGZIP() []byte {
	file_control_proto_rawDescOnce.Do(func() {
		file_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_control_proto_rawDesc), len(file_control_proto_rawDesc)))
	})
	return file_control_proto_rawDescData
}

var file_control_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_control_proto_goTypes = []any{
	(*ControlRequest)(nil),          // 0: vz.control.v1.ControlRequest
	(*ControlResponse)(nil),         // 1: vz.control.v1.ControlResponse
	(*KeyCommand)(nil),              // 2: vz.control.v1.KeyCommand
	(*MouseCommand)(nil),            // 3: vz.control.v1.MouseCommand
	(*TextCommand)(nil),             // 4: vz.control.v1.TextCommand
	(*ScreenshotCommand)(nil),       // 5: vz.control.v1.ScreenshotCommand
	(*SnapshotCommand)(nil),         // 6: vz.control.v1.SnapshotCommand
	(*MemoryCommand)(nil),           // 7: vz.control.v1.MemoryCommand
	(*OCRCommand)(nil),              // 8: vz.control.v1.OCRCommand
	(*PortForwardCommand)(nil),      // 9: vz.control.v1.PortForwardCommand
	(*AgentExecCommand)(nil),        // 10: vz.control.v1.AgentExecCommand
	(*AgentFileReadCommand)(nil),    // 11: vz.control.v1.AgentFileReadCommand
	(*AgentFileWriteCommand)(nil),   // 12: vz.control.v1.AgentFileWriteCommand
	(*AgentShutdownCommand)(nil),    // 13: vz.control.v1.AgentShutdownCommand
	(*AgentSSHDCommand)(nil),        // 14: vz.control.v1.AgentSSHDCommand
	(*AgentCopyCommand)(nil),        // 15: vz.control.v1.AgentCopyCommand
	(*StatusResponse)(nil),          // 16: vz.control.v1.StatusResponse
	(*CapabilitiesResponse)(nil),    // 17: vz.control.v1.CapabilitiesResponse
	(*ScreenshotResponse)(nil),      // 18: vz.control.v1.ScreenshotResponse
	(*EmptyResponse)(nil),           // 19: vz.control.v1.EmptyResponse
	(*SnapshotListResponse)(nil),    // 20: vz.control.v1.SnapshotListResponse
	(*SnapshotActionResponse)(nil),  // 21: vz.control.v1.SnapshotActionResponse
	(*MessageResponse)(nil),         // 22: vz.control.v1.MessageResponse
	(*MemoryInfoResponse)(nil),      // 23: vz.control.v1.MemoryInfoResponse
	(*NetworkInfoResponse)(nil),     // 24: vz.control.v1.NetworkInfoResponse
	(*MemoryInfo)(nil),              // 25: vz.control.v1.MemoryInfo
	(*SnapshotInfo)(nil),            // 26: vz.control.v1.SnapshotInfo
	(*AgentExecResponse)(nil),       // 27: vz.control.v1.AgentExecResponse
	(*AgentFileResponse)(nil),       // 28: vz.control.v1.AgentFileResponse
	(*AgentInfoResponse)(nil),       // 29: vz.control.v1.AgentInfoResponse
	(*AgentPingResponse)(nil),       // 30: vz.control.v1.AgentPingResponse
	(*OCRTextResponse)(nil),         // 31: vz.control.v1.OCRTextResponse
	(*OCRMatch)(nil),                // 32: vz.control.v1.OCRMatch
	(*ScreenDetectionResponse)(nil), // 33: vz.control.v1.ScreenDetectionResponse
	nil,                             // 34: vz.control.v1.AgentExecCommand.EnvEntry
	nil,                             // 35: vz.control.v1.CapabilitiesResponse.FeaturesEntry
}
var file_control_proto_depIdxs = []int32{
	2,  // 0: vz.control.v1.ControlRequest.key:type_name -> vz.control.v1.KeyCommand
	3,  // 1: vz.control.v1.ControlRequest.mouse:type_name -> vz.control.v1.MouseCommand
	4,  // 2: vz.control.v1.ControlRequest.text:type_name -> vz.control.v1.TextCommand
	5,  // 3: vz.control.v1.ControlRequest.screenshot:type_name -> vz.control.v1.ScreenshotCommand
	6,  // 4: vz.control.v1.ControlRequest.snapshot:type_name -> vz.control.v1.SnapshotCommand
	7,  // 5: vz.control.v1.ControlRequest.memory:type_name -> vz.control.v1.MemoryCommand
	8,  // 6: vz.control.v1.ControlRequest.ocr:type_name -> vz.control.v1.OCRCommand
	9,  // 7: vz.control.v1.ControlRequest.port_forward:type_name -> vz.control.v1.PortForwardCommand
	10, // 8: vz.control.v1.ControlRequest.agent_exec:type_name -> vz.control.v1.AgentExecCommand
	11, // 9: vz.control.v1.ControlRequest.agent_read:type_name -> vz.control.v1.AgentFileReadCommand
	12, // 10: vz.control.v1.ControlRequest.agent_write:type_name -> vz.control.v1.AgentFileWriteCommand
	13, // 11: vz.control.v1.ControlRequest.agent_shutdown:type_name -> vz.control.v1.AgentShutdownCommand
	14, // 12: vz.control.v1.ControlRequest.agent_sshd:type_name -> vz.control.v1.AgentSSHDCommand
	15, // 13: vz.control.v1.ControlRequest.agent_cp:type_name -> vz.control.v1.AgentCopyCommand
	16, // 14: vz.control.v1.ControlResponse.status:type_name -> vz.control.v1.StatusResponse
	17, // 15: vz.control.v1.ControlResponse.capabilities:type_name -> vz.control.v1.CapabilitiesResponse
	18, // 16: vz.control.v1.ControlResponse.screenshot_result:type_name -> vz.control.v1.ScreenshotResponse
	19, // 17: vz.control.v1.ControlResponse.empty:type_name -> vz.control.v1.EmptyResponse
	20, // 18: vz.control.v1.ControlResponse.snapshot_list:type_name -> vz.control.v1.SnapshotListResponse
	21, // 19: vz.control.v1.ControlResponse.snapshot_action:type_name -> vz.control.v1.SnapshotActionResponse
	22, // 20: vz.control.v1.ControlResponse.message:type_name -> vz.control.v1.MessageResponse
	24, // 21: vz.control.v1.ControlResponse.network_info:type_name -> vz.control.v1.NetworkInfoResponse
	23, // 22: vz.control.v1.ControlResponse.memory_info:type_name -> vz.control.v1.MemoryInfoResponse
	27, // 23: vz.control.v1.ControlResponse.agent_exec_result:type_name -> vz.control.v1.AgentExecResponse
	28, // 24: vz.control.v1.ControlResponse.agent_file:type_name -> vz.control.v1.AgentFileResponse
	29, // 25: vz.control.v1.ControlResponse.agent_info:type_name -> vz.control.v1.AgentInfoResponse
	30, // 26: vz.control.v1.ControlResponse.agent_ping:type_name -> vz.control.v1.AgentPingResponse
	31, // 27: vz.control.v1.ControlResponse.ocr_text:type_name -> vz.control.v1.OCRTextResponse
	33, // 28: vz.control.v1.ControlResponse.screen_detection:type_name -> vz.control.v1.ScreenDetectionResponse
	34, // 29: vz.control.v1.AgentExecCommand.env:type_name -> vz.control.v1.AgentExecCommand.EnvEntry
	35, // 30: vz.control.v1.CapabilitiesResponse.features:type_name -> vz.control.v1.CapabilitiesResponse.FeaturesEntry
	26, // 31: vz.control.v1.SnapshotListResponse.snapshots:type_name -> vz.control.v1.SnapshotInfo
	25, // 32: vz.control.v1.MemoryInfoResponse.info:type_name -> vz.control.v1.MemoryInfo
	32, // 33: vz.control.v1.OCRTextResponse.matches:type_name -> vz.control.v1.OCRMatch
	34, // [34:34] is the sub-list for method output_type
	34, // [34:34] is the sub-list for method input_type
	34, // [34:34] is the sub-list for extension type_name
	34, // [34:34] is the sub-list for extension extendee
	0,  // [0:34] is the sub-list for field type_name
}

func init() { file_control_proto_init() }
func file_control_proto_init() {
	if File_control_proto != nil {
		return
	}
	file_control_proto_msgTypes[0].OneofWrappers = []any{
		(*ControlRequest_Key)(nil),
		(*ControlRequest_Mouse)(nil),
		(*ControlRequest_Text)(nil),
		(*ControlRequest_Screenshot)(nil),
		(*ControlRequest_Snapshot)(nil),
		(*ControlRequest_Memory)(nil),
		(*ControlRequest_Ocr)(nil),
		(*ControlRequest_PortForward)(nil),
		(*ControlRequest_AgentExec)(nil),
		(*ControlRequest_AgentRead)(nil),
		(*ControlRequest_AgentWrite)(nil),
		(*ControlRequest_AgentShutdown)(nil),
		(*ControlRequest_AgentSshd)(nil),
		(*ControlRequest_AgentCp)(nil),
	}
	file_control_proto_msgTypes[1].OneofWrappers = []any{
		(*ControlResponse_Status)(nil),
		(*ControlResponse_Capabilities)(nil),
		(*ControlResponse_ScreenshotResult)(nil),
		(*ControlResponse_Empty)(nil),
		(*ControlResponse_SnapshotList)(nil),
		(*ControlResponse_SnapshotAction)(nil),
		(*ControlResponse_Message)(nil),
		(*ControlResponse_NetworkInfo)(nil),
		(*ControlResponse_MemoryInfo)(nil),
		(*ControlResponse_AgentExecResult)(nil),
		(*ControlResponse_AgentFile)(nil),
		(*ControlResponse_AgentInfo)(nil),
		(*ControlResponse_AgentPing)(nil),
		(*ControlResponse_OcrText)(nil),
		(*ControlResponse_ScreenDetection)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_control_proto_rawDesc), len(file_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_control_proto_goTypes,
		DependencyIndexes: file_control_proto_depIdxs,
		MessageInfos:      file_control_proto_msgTypes,
	}.Build()
	File_control_proto = out.File
	file_control_proto_goTypes = nil
	file_control_proto_depIdxs = nil
}
