// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: control.proto

package controlpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ControlRequest is the envelope for all control socket requests.
// Every JSON line sent to the socket is unmarshaled into this message.
// The "type" field selects the handler; the oneof carries the payload.
type ControlRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Command type string for dispatch (e.g. "key", "screenshot", "ping").
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Types that are valid to be assigned to Command:
	//
	//	*ControlRequest_Key
	//	*ControlRequest_Mouse
	//	*ControlRequest_Text
	//	*ControlRequest_Screenshot
	//	*ControlRequest_Snapshot
	//	*ControlRequest_Memory
	//	*ControlRequest_AgentExec
	//	*ControlRequest_AgentRead
	//	*ControlRequest_AgentWrite
	//	*ControlRequest_AgentShutdown
	//	*ControlRequest_AgentSshd
	//	*ControlRequest_AgentCp
	Command       isControlRequest_Command `protobuf_oneof:"command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlRequest) Reset() {
	*x = ControlRequest{}
	mi := &file_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlRequest) ProtoMessage() {}

func (x *ControlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlRequest.ProtoReflect.Descriptor instead.
func (*ControlRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{0}
}

func (x *ControlRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ControlRequest) GetCommand() isControlRequest_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *ControlRequest) GetKey() *KeyCommand {
	if x != nil {
		if x, ok := x.Command.(*ControlRequest_Key); ok {
			return x.Key
		}
	}
	return nil
}

func (x *ControlRequest) GetMouse() *MouseCommand {
	if x != nil {
		if x, ok := x.Command.(*ControlRequest_Mouse); ok {
			return x.Mouse
		}
	}
	return nil
}

func (x *ControlRequest) GetText() *TextCommand {
	if x != nil {
		if x, ok := x.Command.(*ControlRequest_Text); ok {
			return x.Text
		}
	}
	return nil
}

func (x *ControlRequest) GetScreenshot() *ScreenshotCommand {
	if x != nil {
		if x, ok := x.Command.(*ControlRequest_Screenshot); ok {
			return x.Screenshot
		}
	}
	return nil
}

func (x *ControlRequest) GetSnapshot() *SnapshotCommand {
	if x != nil {
		if x, ok := x.Command.(*ControlRequest_Snapshot); ok {
			return x.Snapshot
		}
	}
	return nil
}

func (x *ControlRequest) GetMemory() *MemoryCommand {
	if x != nil {
		if x, ok := x.Command.(*ControlRequest_Memory); ok {
			return x.Memory
		}
	}
	return nil
}

func (x *ControlRequest) GetAgentExec() *AgentExecCommand {
	if x != nil {
		if x, ok := x.Command.(*ControlRequest_AgentExec); ok {
			return x.AgentExec
		}
	}
	return nil
}

func (x *ControlRequest) GetAgentRead() *AgentFileReadCommand {
	if x != nil {
		if x, ok := x.Command.(*ControlRequest_AgentRead); ok {
			return x.AgentRead
		}
	}
	return nil
}

func (x *ControlRequest) GetAgentWrite() *AgentFileWriteCommand {
	if x != nil {
		if x, ok := x.Command.(*ControlRequest_AgentWrite); ok {
			return x.AgentWrite
		}
	}
	return nil
}

func (x *ControlRequest) GetAgentShutdown() *AgentShutdownCommand {
	if x != nil {
		if x, ok := x.Command.(*ControlRequest_AgentShutdown); ok {
			return x.AgentShutdown
		}
	}
	return nil
}

func (x *ControlRequest) GetAgentSshd() *AgentSSHDCommand {
	if x != nil {
		if x, ok := x.Command.(*ControlRequest_AgentSshd); ok {
			return x.AgentSshd
		}
	}
	return nil
}

func (x *ControlRequest) GetAgentCp() *AgentCopyCommand {
	if x != nil {
		if x, ok := x.Command.(*ControlRequest_AgentCp); ok {
			return x.AgentCp
		}
	}
	return nil
}

type isControlRequest_Command interface {
	isControlRequest_Command()
}

type ControlRequest_Key struct {
	Key *KeyCommand `protobuf:"bytes,10,opt,name=key,proto3,oneof"`
}

type ControlRequest_Mouse struct {
	Mouse *MouseCommand `protobuf:"bytes,11,opt,name=mouse,proto3,oneof"`
}

type ControlRequest_Text struct {
	Text *TextCommand `protobuf:"bytes,12,opt,name=text,proto3,oneof"`
}

type ControlRequest_Screenshot struct {
	Screenshot *ScreenshotCommand `protobuf:"bytes,13,opt,name=screenshot,proto3,oneof"`
}

type ControlRequest_Snapshot struct {
	Snapshot *SnapshotCommand `protobuf:"bytes,14,opt,name=snapshot,proto3,oneof"`
}

type ControlRequest_Memory struct {
	Memory *MemoryCommand `protobuf:"bytes,15,opt,name=memory,proto3,oneof"`
}

type ControlRequest_AgentExec struct {
	AgentExec *AgentExecCommand `protobuf:"bytes,20,opt,name=agent_exec,json=agentExec,proto3,oneof"`
}

type ControlRequest_AgentRead struct {
	AgentRead *AgentFileReadCommand `protobuf:"bytes,21,opt,name=agent_read,json=agentRead,proto3,oneof"`
}

type ControlRequest_AgentWrite struct {
	AgentWrite *AgentFileWriteCommand `protobuf:"bytes,22,opt,name=agent_write,json=agentWrite,proto3,oneof"`
}

type ControlRequest_AgentShutdown struct {
	AgentShutdown *AgentShutdownCommand `protobuf:"bytes,23,opt,name=agent_shutdown,json=agentShutdown,proto3,oneof"`
}

type ControlRequest_AgentSshd struct {
	AgentSshd *AgentSSHDCommand `protobuf:"bytes,24,opt,name=agent_sshd,json=agentSshd,proto3,oneof"`
}

type ControlRequest_AgentCp struct {
	AgentCp *AgentCopyCommand `protobuf:"bytes,25,opt,name=agent_cp,json=agentCp,proto3,oneof"`
}

func (*ControlRequest_Key) isControlRequest_Command() {}

func (*ControlRequest_Mouse) isControlRequest_Command() {}

func (*ControlRequest_Text) isControlRequest_Command() {}

func (*ControlRequest_Screenshot) isControlRequest_Command() {}

func (*ControlRequest_Snapshot) isControlRequest_Command() {}

func (*ControlRequest_Memory) isControlRequest_Command() {}

func (*ControlRequest_AgentExec) isControlRequest_Command() {}

func (*ControlRequest_AgentRead) isControlRequest_Command() {}

func (*ControlRequest_AgentWrite) isControlRequest_Command() {}

func (*ControlRequest_AgentShutdown) isControlRequest_Command() {}

func (*ControlRequest_AgentSshd) isControlRequest_Command() {}

func (*ControlRequest_AgentCp) isControlRequest_Command() {}

// ControlResponse is the envelope for all control socket responses.
type ControlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlResponse) Reset() {
	*x = ControlResponse{}
	mi := &file_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlResponse) ProtoMessage() {}

func (x *ControlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlResponse.ProtoReflect.Descriptor instead.
func (*ControlResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{1}
}

func (x *ControlResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ControlResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ControlResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

// KeyCommand sends a keyboard event to the VM.
type KeyCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyCode       uint32                 `protobuf:"varint,1,opt,name=key_code,json=keyCode,proto3" json:"key_code,omitempty"`
	Character     string                 `protobuf:"bytes,2,opt,name=character,proto3" json:"character,omitempty"`
	Modifiers     uint32                 `protobuf:"varint,3,opt,name=modifiers,proto3" json:"modifiers,omitempty"`
	KeyDown       bool                   `protobuf:"varint,4,opt,name=key_down,json=keyDown,proto3" json:"key_down,omitempty"`
	UseCgEvent    bool                   `protobuf:"varint,5,opt,name=use_cg_event,json=useCgEvent,proto3" json:"use_cg_event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyCommand) Reset() {
	*x = KeyCommand{}
	mi := &file_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyCommand) ProtoMessage() {}

func (x *KeyCommand) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyCommand.ProtoReflect.Descriptor instead.
func (*KeyCommand) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{2}
}

func (x *KeyCommand) GetKeyCode() uint32 {
	if x != nil {
		return x.KeyCode
	}
	return 0
}

func (x *KeyCommand) GetCharacter() string {
	if x != nil {
		return x.Character
	}
	return ""
}

func (x *KeyCommand) GetModifiers() uint32 {
	if x != nil {
		return x.Modifiers
	}
	return 0
}

func (x *KeyCommand) GetKeyDown() bool {
	if x != nil {
		return x.KeyDown
	}
	return false
}

func (x *KeyCommand) GetUseCgEvent() bool {
	if x != nil {
		return x.UseCgEvent
	}
	return false
}

// MouseCommand sends a mouse event to the VM.
type MouseCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	Button        int32                  `protobuf:"varint,3,opt,name=button,proto3" json:"button,omitempty"`
	Action        string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	ScrollX       float64                `protobuf:"fixed64,5,opt,name=scroll_x,json=scrollX,proto3" json:"scroll_x,omitempty"`
	ScrollY       float64                `protobuf:"fixed64,6,opt,name=scroll_y,json=scrollY,proto3" json:"scroll_y,omitempty"`
	Absolute      bool                   `protobuf:"varint,7,opt,name=absolute,proto3" json:"absolute,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MouseCommand) Reset() {
	*x = MouseCommand{}
	mi := &file_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MouseCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MouseCommand) ProtoMessage() {}

func (x *MouseCommand) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MouseCommand.ProtoReflect.Descriptor instead.
func (*MouseCommand) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{3}
}

func (x *MouseCommand) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *MouseCommand) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *MouseCommand) GetButton() int32 {
	if x != nil {
		return x.Button
	}
	return 0
}

func (x *MouseCommand) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *MouseCommand) GetScrollX() float64 {
	if x != nil {
		return x.ScrollX
	}
	return 0
}

func (x *MouseCommand) GetScrollY() float64 {
	if x != nil {
		return x.ScrollY
	}
	return 0
}

func (x *MouseCommand) GetAbsolute() bool {
	if x != nil {
		return x.Absolute
	}
	return false
}

// TextCommand types a string of text character by character.
type TextCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextCommand) Reset() {
	*x = TextCommand{}
	mi := &file_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextCommand) ProtoMessage() {}

func (x *TextCommand) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextCommand.ProtoReflect.Descriptor instead.
func (*TextCommand) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{4}
}

func (x *TextCommand) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// ScreenshotCommand captures the VM display.
type ScreenshotCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Diff          bool                   `protobuf:"varint,1,opt,name=diff,proto3" json:"diff,omitempty"`
	Scale         float64                `protobuf:"fixed64,2,opt,name=scale,proto3" json:"scale,omitempty"`
	Quality       int32                  `protobuf:"varint,3,opt,name=quality,proto3" json:"quality,omitempty"`
	Format        string                 `protobuf:"bytes,4,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScreenshotCommand) Reset() {
	*x = ScreenshotCommand{}
	mi := &file_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreenshotCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreenshotCommand) ProtoMessage() {}

func (x *ScreenshotCommand) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreenshotCommand.ProtoReflect.Descriptor instead.
func (*ScreenshotCommand) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{5}
}

func (x *ScreenshotCommand) GetDiff() bool {
	if x != nil {
		return x.Diff
	}
	return false
}

func (x *ScreenshotCommand) GetScale() float64 {
	if x != nil {
		return x.Scale
	}
	return 0
}

func (x *ScreenshotCommand) GetQuality() int32 {
	if x != nil {
		return x.Quality
	}
	return 0
}

func (x *ScreenshotCommand) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

// SnapshotCommand manages VM state snapshots.
type SnapshotCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotCommand) Reset() {
	*x = SnapshotCommand{}
	mi := &file_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotCommand) ProtoMessage() {}

func (x *SnapshotCommand) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotCommand.ProtoReflect.Descriptor instead.
func (*SnapshotCommand) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{6}
}

func (x *SnapshotCommand) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *SnapshotCommand) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// MemoryCommand manages runtime memory balloon.
type MemoryCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	SizeGb        float64                `protobuf:"fixed64,2,opt,name=size_gb,json=sizeGb,proto3" json:"size_gb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryCommand) Reset() {
	*x = MemoryCommand{}
	mi := &file_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryCommand) ProtoMessage() {}

func (x *MemoryCommand) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryCommand.ProtoReflect.Descriptor instead.
func (*MemoryCommand) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{7}
}

func (x *MemoryCommand) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *MemoryCommand) GetSizeGb() float64 {
	if x != nil {
		return x.SizeGb
	}
	return 0
}

// NetworkInfoResponse contains VM network configuration.
type NetworkInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MacAddress    string                 `protobuf:"bytes,1,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	GuestIp       string                 `protobuf:"bytes,2,opt,name=guest_ip,json=guestIp,proto3" json:"guest_ip,omitempty"`
	Mode          string                 `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkInfoResponse) Reset() {
	*x = NetworkInfoResponse{}
	mi := &file_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkInfoResponse) ProtoMessage() {}

func (x *NetworkInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkInfoResponse.ProtoReflect.Descriptor instead.
func (*NetworkInfoResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{8}
}

func (x *NetworkInfoResponse) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *NetworkInfoResponse) GetGuestIp() string {
	if x != nil {
		return x.GuestIp
	}
	return ""
}

func (x *NetworkInfoResponse) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

// MemoryInfo contains information about VM memory configuration.
type MemoryInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ConfiguredGb     float64                `protobuf:"fixed64,1,opt,name=configured_gb,json=configuredGb,proto3" json:"configured_gb,omitempty"`
	TargetGb         float64                `protobuf:"fixed64,2,opt,name=target_gb,json=targetGb,proto3" json:"target_gb,omitempty"`
	MinimumAllowedMb uint64                 `protobuf:"varint,3,opt,name=minimum_allowed_mb,json=minimumAllowedMb,proto3" json:"minimum_allowed_mb,omitempty"`
	HasBalloon       bool                   `protobuf:"varint,4,opt,name=has_balloon,json=hasBalloon,proto3" json:"has_balloon,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MemoryInfo) Reset() {
	*x = MemoryInfo{}
	mi := &file_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryInfo) ProtoMessage() {}

func (x *MemoryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryInfo.ProtoReflect.Descriptor instead.
func (*MemoryInfo) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{9}
}

func (x *MemoryInfo) GetConfiguredGb() float64 {
	if x != nil {
		return x.ConfiguredGb
	}
	return 0
}

func (x *MemoryInfo) GetTargetGb() float64 {
	if x != nil {
		return x.TargetGb
	}
	return 0
}

func (x *MemoryInfo) GetMinimumAllowedMb() uint64 {
	if x != nil {
		return x.MinimumAllowedMb
	}
	return 0
}

func (x *MemoryInfo) GetHasBalloon() bool {
	if x != nil {
		return x.HasBalloon
	}
	return false
}

// SnapshotInfo contains metadata about a saved snapshot.
type SnapshotInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Created       string                 `protobuf:"bytes,2,opt,name=created,proto3" json:"created,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	VmState       string                 `protobuf:"bytes,4,opt,name=vm_state,json=vmState,proto3" json:"vm_state,omitempty"`
	FilePath      string                 `protobuf:"bytes,5,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotInfo) Reset() {
	*x = SnapshotInfo{}
	mi := &file_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotInfo) ProtoMessage() {}

func (x *SnapshotInfo) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotInfo.ProtoReflect.Descriptor instead.
func (*SnapshotInfo) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{10}
}

func (x *SnapshotInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SnapshotInfo) GetCreated() string {
	if x != nil {
		return x.Created
	}
	return ""
}

func (x *SnapshotInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *SnapshotInfo) GetVmState() string {
	if x != nil {
		return x.VmState
	}
	return ""
}

func (x *SnapshotInfo) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

// AgentExecCommand runs a command inside the guest.
type AgentExecCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Args          []string               `protobuf:"bytes,1,rep,name=args,proto3" json:"args,omitempty"`
	Env           map[string]string      `protobuf:"bytes,2,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	WorkingDir    string                 `protobuf:"bytes,3,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentExecCommand) Reset() {
	*x = AgentExecCommand{}
	mi := &file_control_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentExecCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentExecCommand) ProtoMessage() {}

func (x *AgentExecCommand) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentExecCommand.ProtoReflect.Descriptor instead.
func (*AgentExecCommand) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{11}
}

func (x *AgentExecCommand) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *AgentExecCommand) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *AgentExecCommand) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

// AgentFileReadCommand reads a file from the guest.
type AgentFileReadCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentFileReadCommand) Reset() {
	*x = AgentFileReadCommand{}
	mi := &file_control_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentFileReadCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentFileReadCommand) ProtoMessage() {}

func (x *AgentFileReadCommand) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentFileReadCommand.ProtoReflect.Descriptor instead.
func (*AgentFileReadCommand) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{12}
}

func (x *AgentFileReadCommand) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// AgentFileWriteCommand writes a file to the guest.
type AgentFileWriteCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Data          string                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Mode          uint32                 `protobuf:"varint,3,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentFileWriteCommand) Reset() {
	*x = AgentFileWriteCommand{}
	mi := &file_control_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentFileWriteCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentFileWriteCommand) ProtoMessage() {}

func (x *AgentFileWriteCommand) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentFileWriteCommand.ProtoReflect.Descriptor instead.
func (*AgentFileWriteCommand) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{13}
}

func (x *AgentFileWriteCommand) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *AgentFileWriteCommand) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *AgentFileWriteCommand) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

// AgentShutdownCommand triggers a graceful shutdown.
type AgentShutdownCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Force         bool                   `protobuf:"varint,1,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentShutdownCommand) Reset() {
	*x = AgentShutdownCommand{}
	mi := &file_control_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentShutdownCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentShutdownCommand) ProtoMessage() {}

func (x *AgentShutdownCommand) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentShutdownCommand.ProtoReflect.Descriptor instead.
func (*AgentShutdownCommand) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{14}
}

func (x *AgentShutdownCommand) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

// AgentSSHDCommand manages sshd via systemsetup.
type AgentSSHDCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentSSHDCommand) Reset() {
	*x = AgentSSHDCommand{}
	mi := &file_control_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentSSHDCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentSSHDCommand) ProtoMessage() {}

func (x *AgentSSHDCommand) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentSSHDCommand.ProtoReflect.Descriptor instead.
func (*AgentSSHDCommand) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{15}
}

func (x *AgentSSHDCommand) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

// AgentCopyCommand copies files between host and guest using streaming gRPC.
// Direction is determined by the presence of host_path and guest_path:
//   - host_path set + guest_path set: copy host→guest (to_guest=true) or guest→host (to_guest=false)
type AgentCopyCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostPath      string                 `protobuf:"bytes,1,opt,name=host_path,json=hostPath,proto3" json:"host_path,omitempty"`
	GuestPath     string                 `protobuf:"bytes,2,opt,name=guest_path,json=guestPath,proto3" json:"guest_path,omitempty"`
	ToGuest       bool                   `protobuf:"varint,3,opt,name=to_guest,json=toGuest,proto3" json:"to_guest,omitempty"`
	Mode          uint32                 `protobuf:"varint,4,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentCopyCommand) Reset() {
	*x = AgentCopyCommand{}
	mi := &file_control_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentCopyCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentCopyCommand) ProtoMessage() {}

func (x *AgentCopyCommand) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentCopyCommand.ProtoReflect.Descriptor instead.
func (*AgentCopyCommand) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{16}
}

func (x *AgentCopyCommand) GetHostPath() string {
	if x != nil {
		return x.HostPath
	}
	return ""
}

func (x *AgentCopyCommand) GetGuestPath() string {
	if x != nil {
		return x.GuestPath
	}
	return ""
}

func (x *AgentCopyCommand) GetToGuest() bool {
	if x != nil {
		return x.ToGuest
	}
	return false
}

func (x *AgentCopyCommand) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

var File_control_proto protoreflect.FileDescriptor

const file_control_proto_rawDesc = "" +
	"\n" +
	"\rcontrol.proto\x12\rvz.control.v1\"\x9e\x06\n" +
	"\x0eControlRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12-\n" +
	"\x03key\x18\n" +
	" \x01(\v2\x19.vz.control.v1.KeyCommandH\x00R\x03key\x123\n" +
	"\x05mouse\x18\v \x01(\v2\x1b.vz.control.v1.MouseCommandH\x00R\x05mouse\x120\n" +
	"\x04text\x18\f \x01(\v2\x1a.vz.control.v1.TextCommandH\x00R\x04text\x12B\n" +
	"\n" +
	"screenshot\x18\r \x01(\v2 .vz.control.v1.ScreenshotCommandH\x00R\n" +
	"screenshot\x12<\n" +
	"\bsnapshot\x18\x0e \x01(\v2\x1e.vz.control.v1.SnapshotCommandH\x00R\bsnapshot\x126\n" +
	"\x06memory\x18\x0f \x01(\v2\x1c.vz.control.v1.MemoryCommandH\x00R\x06memory\x12@\n" +
	"\n" +
	"agent_exec\x18\x14 \x01(\v2\x1f.vz.control.v1.AgentExecCommandH\x00R\tagentExec\x12D\n" +
	"\n" +
	"agent_read\x18\x15 \x01(\v2#.vz.control.v1.AgentFileReadCommandH\x00R\tagentRead\x12G\n" +
	"\vagent_write\x18\x16 \x01(\v2$.vz.control.v1.AgentFileWriteCommandH\x00R\n" +
	"agentWrite\x12L\n" +
	"\x0eagent_shutdown\x18\x17 \x01(\v2#.vz.control.v1.AgentShutdownCommandH\x00R\ragentShutdown\x12@\n" +
	"\n" +
	"agent_sshd\x18\x18 \x01(\v2\x1f.vz.control.v1.AgentSSHDCommandH\x00R\tagentSshd\x12<\n" +
	"\bagent_cp\x18\x19 \x01(\v2\x1f.vz.control.v1.AgentCopyCommandH\x00R\aagentCpB\t\n" +
	"\acommand\"U\n" +
	"\x0fControlResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data\"\xa0\x01\n" +
	"\n" +
	"KeyCommand\x12\x19\n" +
	"\bkey_code\x18\x01 \x01(\rR\akeyCode\x12\x1c\n" +
	"\tcharacter\x18\x02 \x01(\tR\tcharacter\x12\x1c\n" +
	"\tmodifiers\x18\x03 \x01(\rR\tmodifiers\x12\x19\n" +
	"\bkey_down\x18\x04 \x01(\bR\akeyDown\x12 \n" +
	"\fuse_cg_event\x18\x05 \x01(\bR\n" +
	"useCgEvent\"\xac\x01\n" +
	"\fMouseCommand\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\x12\x16\n" +
	"\x06button\x18\x03 \x01(\x05R\x06button\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x12\x19\n" +
	"\bscroll_x\x18\x05 \x01(\x01R\ascrollX\x12\x19\n" +
	"\bscroll_y\x18\x06 \x01(\x01R\ascrollY\x12\x1a\n" +
	"\babsolute\x18\a \x01(\bR\babsolute\"!\n" +
	"\vTextCommand\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"o\n" +
	"\x11ScreenshotCommand\x12\x12\n" +
	"\x04diff\x18\x01 \x01(\bR\x04diff\x12\x14\n" +
	"\x05scale\x18\x02 \x01(\x01R\x05scale\x12\x18\n" +
	"\aquality\x18\x03 \x01(\x05R\aquality\x12\x16\n" +
	"\x06format\x18\x04 \x01(\tR\x06format\"=\n" +
	"\x0fSnapshotCommand\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"@\n" +
	"\rMemoryCommand\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x17\n" +
	"\asize_gb\x18\x02 \x01(\x01R\x06sizeGb\"e\n" +
	"\x13NetworkInfoResponse\x12\x1f\n" +
	"\vmac_address\x18\x01 \x01(\tR\n" +
	"macAddress\x12\x19\n" +
	"\bguest_ip\x18\x02 \x01(\tR\aguestIp\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\tR\x04mode\"\x9d\x01\n" +
	"\n" +
	"MemoryInfo\x12#\n" +
	"\rconfigured_gb\x18\x01 \x01(\x01R\fconfiguredGb\x12\x1b\n" +
	"\ttarget_gb\x18\x02 \x01(\x01R\btargetGb\x12,\n" +
	"\x12minimum_allowed_mb\x18\x03 \x01(\x04R\x10minimumAllowedMb\x12\x1f\n" +
	"\vhas_balloon\x18\x04 \x01(\bR\n" +
	"hasBalloon\"\x88\x01\n" +
	"\fSnapshotInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acreated\x18\x02 \x01(\tR\acreated\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x19\n" +
	"\bvm_state\x18\x04 \x01(\tR\avmState\x12\x1b\n" +
	"\tfile_path\x18\x05 \x01(\tR\bfilePath\"\xbb\x01\n" +
	"\x10AgentExecCommand\x12\x12\n" +
	"\x04args\x18\x01 \x03(\tR\x04args\x12:\n" +
	"\x03env\x18\x02 \x03(\v2(.vz.control.v1.AgentExecCommand.EnvEntryR\x03env\x12\x1f\n" +
	"\vworking_dir\x18\x03 \x01(\tR\n" +
	"workingDir\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"*\n" +
	"\x14AgentFileReadCommand\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"S\n" +
	"\x15AgentFileWriteCommand\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04data\x18\x02 \x01(\tR\x04data\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\rR\x04mode\",\n" +
	"\x14AgentShutdownCommand\x12\x14\n" +
	"\x05force\x18\x01 \x01(\bR\x05force\"*\n" +
	"\x10AgentSSHDCommand\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\"}\n" +
	"\x10AgentCopyCommand\x12\x1b\n" +
	"\thost_path\x18\x01 \x01(\tR\bhostPath\x12\x1d\n" +
	"\n" +
	"guest_path\x18\x02 \x01(\tR\tguestPath\x12\x19\n" +
	"\bto_guest\x18\x03 \x01(\bR\atoGuest\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\rR\x04modeB)Z'github.com/tmc/vz-macos/proto/controlpbb\x06proto3"

var (
	file_control_proto_rawDescOnce sync.Once
	file_control_proto_rawDescData []byte
)

func file_control_proto_rawDescGZIP() []byte {
	file_control_proto_rawDescOnce.Do(func() {
		file_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_control_proto_rawDesc), len(file_control_proto_rawDesc)))
	})
	return file_control_proto_rawDescData
}

var file_control_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_control_proto_goTypes = []any{
	(*ControlRequest)(nil),        // 0: vz.control.v1.ControlRequest
	(*ControlResponse)(nil),       // 1: vz.control.v1.ControlResponse
	(*KeyCommand)(nil),            // 2: vz.control.v1.KeyCommand
	(*MouseCommand)(nil),          // 3: vz.control.v1.MouseCommand
	(*TextCommand)(nil),           // 4: vz.control.v1.TextCommand
	(*ScreenshotCommand)(nil),     // 5: vz.control.v1.ScreenshotCommand
	(*SnapshotCommand)(nil),       // 6: vz.control.v1.SnapshotCommand
	(*MemoryCommand)(nil),         // 7: vz.control.v1.MemoryCommand
	(*NetworkInfoResponse)(nil),   // 8: vz.control.v1.NetworkInfoResponse
	(*MemoryInfo)(nil),            // 9: vz.control.v1.MemoryInfo
	(*SnapshotInfo)(nil),          // 10: vz.control.v1.SnapshotInfo
	(*AgentExecCommand)(nil),      // 11: vz.control.v1.AgentExecCommand
	(*AgentFileReadCommand)(nil),  // 12: vz.control.v1.AgentFileReadCommand
	(*AgentFileWriteCommand)(nil), // 13: vz.control.v1.AgentFileWriteCommand
	(*AgentShutdownCommand)(nil),  // 14: vz.control.v1.AgentShutdownCommand
	(*AgentSSHDCommand)(nil),      // 15: vz.control.v1.AgentSSHDCommand
	(*AgentCopyCommand)(nil),      // 16: vz.control.v1.AgentCopyCommand
	nil,                           // 17: vz.control.v1.AgentExecCommand.EnvEntry
}
var file_control_proto_depIdxs = []int32{
	2,  // 0: vz.control.v1.ControlRequest.key:type_name -> vz.control.v1.KeyCommand
	3,  // 1: vz.control.v1.ControlRequest.mouse:type_name -> vz.control.v1.MouseCommand
	4,  // 2: vz.control.v1.ControlRequest.text:type_name -> vz.control.v1.TextCommand
	5,  // 3: vz.control.v1.ControlRequest.screenshot:type_name -> vz.control.v1.ScreenshotCommand
	6,  // 4: vz.control.v1.ControlRequest.snapshot:type_name -> vz.control.v1.SnapshotCommand
	7,  // 5: vz.control.v1.ControlRequest.memory:type_name -> vz.control.v1.MemoryCommand
	11, // 6: vz.control.v1.ControlRequest.agent_exec:type_name -> vz.control.v1.AgentExecCommand
	12, // 7: vz.control.v1.ControlRequest.agent_read:type_name -> vz.control.v1.AgentFileReadCommand
	13, // 8: vz.control.v1.ControlRequest.agent_write:type_name -> vz.control.v1.AgentFileWriteCommand
	14, // 9: vz.control.v1.ControlRequest.agent_shutdown:type_name -> vz.control.v1.AgentShutdownCommand
	15, // 10: vz.control.v1.ControlRequest.agent_sshd:type_name -> vz.control.v1.AgentSSHDCommand
	16, // 11: vz.control.v1.ControlRequest.agent_cp:type_name -> vz.control.v1.AgentCopyCommand
	17, // 12: vz.control.v1.AgentExecCommand.env:type_name -> vz.control.v1.AgentExecCommand.EnvEntry
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_control_proto_init() }
func file_control_proto_init() {
	if File_control_proto != nil {
		return
	}
	file_control_proto_msgTypes[0].OneofWrappers = []any{
		(*ControlRequest_Key)(nil),
		(*ControlRequest_Mouse)(nil),
		(*ControlRequest_Text)(nil),
		(*ControlRequest_Screenshot)(nil),
		(*ControlRequest_Snapshot)(nil),
		(*ControlRequest_Memory)(nil),
		(*ControlRequest_AgentExec)(nil),
		(*ControlRequest_AgentRead)(nil),
		(*ControlRequest_AgentWrite)(nil),
		(*ControlRequest_AgentShutdown)(nil),
		(*ControlRequest_AgentSshd)(nil),
		(*ControlRequest_AgentCp)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_control_proto_rawDesc), len(file_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_control_proto_goTypes,
		DependencyIndexes: file_control_proto_depIdxs,
		MessageInfos:      file_control_proto_msgTypes,
	}.Build()
	File_control_proto = out.File
	file_control_proto_goTypes = nil
	file_control_proto_depIdxs = nil
}
