#!/bin/sh
set -eu

python3 - "$@" <<'PY'
import pathlib
import re
import sys

root = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else ".")

func_re = re.compile(r"^func\s+(Test\w+|Benchmark\w+|Example\w*)\s*\(")
home_re = re.compile(r't\.Setenv\(\s*"HOME"\s*,|\bwithTempHome\(\s*t\s*\)')
hazards = [
    ("vmconfig.BaseDir()", re.compile(r"\bvmconfig\.BaseDir\(\)|\bBaseDir\(\)")),
    ("vmconfig.Path()", re.compile(r"\bvmconfig\.Path\(")),
    ("vmconfig.EnsureDir()", re.compile(r"\bvmconfig\.EnsureDir\(")),
    ("vmconfig.RunsDir()", re.compile(r"\bvmconfig\.RunsDir\(\)|\bRunsDir\(\)")),
    ("ImagesBaseDir()", re.compile(r"\bImagesBaseDir\(\)")),
    ("~/.vz path literal", re.compile(r'"[^"]*\.vz/|`[^`]*\.vz/')),
]
remove_all_re = re.compile(r"\bos\.RemoveAll\(")


def brace_delta(line: str) -> int:
    # Good enough for Go test bodies. This is an audit aid, not a parser.
    return line.count("{") - line.count("}")


def line_is_comment(line: str) -> bool:
    return line.lstrip().startswith("//")


def severity(kind: str, line: str) -> str:
    if remove_all_re.search(line):
        return "high"
    if kind in {"vmconfig.BaseDir()", "vmconfig.Path()", "vmconfig.EnsureDir()", "ImagesBaseDir()"}:
        return "medium"
    return "low"


findings = []
checked_files = 0
for path in sorted(root.rglob("*_test.go")):
    if ".git" in path.parts or "vendor" in path.parts:
        continue
    checked_files += 1
    rel = path.relative_to(root)
    lines = path.read_text(errors="replace").splitlines()
    in_func = False
    func_name = ""
    depth = 0
    home_line = 0

    for i, line in enumerate(lines, 1):
        if not in_func:
            m = func_re.match(line)
            if not m:
                continue
            in_func = True
            func_name = m.group(1)
            depth = brace_delta(line)
            home_line = 0

        if line_is_comment(line):
            depth += brace_delta(line)
            if depth <= 0:
                in_func = False
            continue

        if home_re.search(line) and home_line == 0:
            home_line = i

        for kind, rx in hazards:
            if not rx.search(line):
                continue
            if home_line and home_line < i:
                continue
            findings.append(
                {
                    "file": str(rel),
                    "line": i,
                    "func": func_name,
                    "kind": kind,
                    "severity": severity(kind, line),
                    "text": line.strip(),
                    "home": home_line,
                }
            )

        if remove_all_re.search(line):
            destructive = any(rx.search(line) for _, rx in hazards) or ".vz" in line
            if destructive and not (home_line and home_line < i):
                findings.append(
                    {
                        "file": str(rel),
                        "line": i,
                        "func": func_name,
                        "kind": "destructive RemoveAll before HOME",
                        "severity": "high",
                        "text": line.strip(),
                        "home": home_line,
                    }
                )

        depth += brace_delta(line)
        if depth <= 0:
            in_func = False

print("# Test HOME Audit")
print()
print("This report is generated by `tools/audit-test-home.sh`.")
print()
print("Rule: tests must call `t.Setenv(\"HOME\", t.TempDir())` before any code that resolves `~/.vz`, including `vmconfig.BaseDir`, `vmconfig.Path`, `vmconfig.EnsureDir`, `vmconfig.RunsDir`, or `ImagesBaseDir`. Tests must not call `os.RemoveAll(vmconfig.BaseDir())` as a fresh-slate hook.")
print()
print(f"Scanned `{checked_files}` Go test files.")
print()

if not findings:
    print("## Findings")
    print()
    print("No hazards found.")
    sys.exit(0)

print("## Findings")
print()
for f in findings:
    if f["severity"] == "high":
        fix = "Set HOME before this line, or remove the destructive cleanup."
    elif f["severity"] == "medium":
        fix = "Set HOME at the start of the test before resolving vmconfig paths."
    else:
        fix = "Review whether this `~/.vz` path is intentionally isolated."
    print(f"- `{f['file']}:{f['line']}` `{f['func']}` severity={f['severity']} kind={f['kind']}")
    print(f"  - code: `{f['text']}`")
    print(f"  - suggested fix: {fix}")
print()

counts = {}
for f in findings:
    counts[f["severity"]] = counts.get(f["severity"], 0) + 1
print("## Summary")
print()
for sev in ("high", "medium", "low"):
    print(f"- {sev}: {counts.get(sev, 0)}")
PY
